import {
  Incident,
  Device,
  CameraFeed,
  AcousticSensorReading,
  SatelliteChangeRecord,
  TimberTransportRecord,
  LegalDocument,
  EvidenceItem,
  InvestigationCase,
  FieldPatrolTeam,
  AuditLogEntry,
  UserProfile,
  ForestRegion,
  SupplyChainFacility,
  BiodiversityRecord,
  ComplianceRecord,
  EnvironmentalRiskDomain,
  AiFindingLevel,
  TargetUserPerspective,
} from '../types/forestguard';

export const CURRENT_USER: UserProfile = {
  id: 'usr-admin-01',
  name: 'Commander Elena Vance',
  email: 'theinhtike201032@gmail.com',
  role: 'SUPER_ADMIN',
  agency: 'Department of Forest Conservation & Environmental Enforcement',
  assignedRegion: 'Amazonian North Basin & Tapir Ridge Biosphere',
  badgeNumber: 'FG-0941',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const AVAILABLE_ROLES: { role: UserProfile['role']; label: string; desc: string }[] = [
  { role: 'SUPER_ADMIN', label: 'Super Admin', desc: 'Full root access to command center, AI models, RBAC, and system audit.' },
  { role: 'SYSTEM_ADMIN', label: 'System Administrator', desc: 'Device telemetry, IoT infrastructure, network firmware, and API bridges.' },
  { role: 'ENVIRONMENT_OFFICER', label: 'Environment Officer', desc: 'Incident triage, satellite canopy review, and reserve zone zoning.' },
  { role: 'FOREST_OFFICER', label: 'Forest Officer', desc: 'Field patrol dispatch, logging permit inspection, and checkpoint controls.' },
  { role: 'FIELD_OFFICER', label: 'Field Officer', desc: 'Mobile operations, evidence capture, offline sync, and patrol pings.' },
  { role: 'INVESTIGATOR', label: 'Investigator', desc: 'Case dossiers, digital evidence vault, chain of custody, and suspect traces.' },
  { role: 'DATA_ANALYST', label: 'Data Analyst', desc: 'Deforestation trends, acoustic frequency analysis, and KPI reporting.' },
  { role: 'LEGAL_OFFICER', label: 'Legal / Compliance Officer', desc: 'Legal RAG intelligence, prosecutorial referrals, and statutory citations.' },
  { role: 'AUDITOR', label: 'Auditor', desc: 'Immutable audit logs, chain of custody verification, and governance checks.' },
  { role: 'READ_ONLY_VIEWER', label: 'Read-Only Viewer', desc: 'Supervisory overview of map, telemetry, and live status without edit rights.' },
];

export const FOREST_ZONES = [
  { id: 'ZN-01', name: 'Tapir Ridge Strict Nature Reserve', type: 'CORE_PROTECTED', areaHa: 45000, risk: 'HIGH', center: { lat: -3.125, lng: -60.024 } },
  { id: 'ZN-02', name: 'Emerald River Corridor', type: 'BUFFER_ZONE', areaHa: 32000, risk: 'MEDIUM', center: { lat: -3.165, lng: -59.982 } },
  { id: 'ZN-03', name: 'Northern Canopy Wildlife Corridor', type: 'CORE_PROTECTED', areaHa: 68000, risk: 'CRITICAL', center: { lat: -3.082, lng: -60.115 } },
  { id: 'ZN-04', name: 'Blackwood Sustainable Forestry Concession', type: 'MANAGED_CONCESSION', areaHa: 24000, risk: 'LOW', center: { lat: -3.210, lng: -60.055 } },
  { id: 'ZN-05', name: 'Rio Negro Tributary Headwaters', type: 'CORE_PROTECTED', areaHa: 52000, risk: 'HIGH', center: { lat: -3.140, lng: -60.180 } },
  { id: 'ZN-06', name: 'South Slope Biological Station Zone', type: 'RESEARCH_STATION', areaHa: 18000, risk: 'LOW', center: { lat: -3.245, lng: -59.920 } },
  { id: 'ZN-07', name: 'Kupari Border Checkpoint Sector', type: 'TRANSIT_CORRIDOR', areaHa: 12000, risk: 'HIGH', center: { lat: -3.190, lng: -59.880 } },
  { id: 'ZN-08', name: 'Highlands Bamboo & Cloud Forest', type: 'CORE_PROTECTED', areaHa: 38000, risk: 'MEDIUM', center: { lat: -3.050, lng: -60.060 } },
];

export const MOCK_FOREST_REGIONS: ForestRegion[] = [
  {
    id: 'REG-A17',
    name: 'Sector A17 (Tanintharyi Evergreen Corridor)',
    sectorCode: 'Sector A17',
    country: 'Myanmar',
    areaHa: 12480,
    forestCoverPercent: 84,
    recentForestLossPercent: 2.4,
    biodiversityObservationsCount: 126,
    activeAlertsCount: 4,
    climateExposure: 'Moderate',
    environmentalRisk: 'High',
    center: { lat: -3.1425, lng: -60.0384 },
    ecosystemType: 'Primary Lowland Dipterocarp & Evergreen Rainforest',
    description: 'High-biodiversity conservation area with active satellite alerts for canopy disturbance and acoustic chainsaw detections along the eastern river buffer.',
  },
  {
    id: 'REG-TR01',
    name: 'Tapir Ridge Strict Nature Reserve',
    sectorCode: 'Sector TR-01',
    country: 'Amazon Basin / Northern Territory',
    areaHa: 45000,
    forestCoverPercent: 91,
    recentForestLossPercent: 1.1,
    biodiversityObservationsCount: 342,
    activeAlertsCount: 7,
    climateExposure: 'Severe',
    environmentalRisk: 'Critical',
    center: { lat: -3.125, lng: -60.024 },
    ecosystemType: 'Intact Core Primary Rainforest & Peat Swamps',
    description: 'Critical sanctuary for endangered lowland tapir, jaguar, and harpy eagle. Heavily monitored edge perimeter experiencing localized incursions.',
  },
  {
    id: 'REG-ER02',
    name: 'Emerald River Riparian Basin',
    sectorCode: 'Sector ER-02',
    country: 'Amazon Basin / North Basin',
    areaHa: 32000,
    forestCoverPercent: 78,
    recentForestLossPercent: 3.2,
    biodiversityObservationsCount: 198,
    activeAlertsCount: 5,
    climateExposure: 'Moderate',
    environmentalRisk: 'High',
    center: { lat: -3.165, lng: -59.982 },
    ecosystemType: 'Riverine Freshwater Swamp & Seasonal Várzea',
    description: 'Crucial watershed and aquatic life corridor. Primary transport arterial subjected to unauthorized barge movements and timber rafting.',
  },
  {
    id: 'REG-NC03',
    name: 'Northern Canopy Wildlife Corridor',
    sectorCode: 'Sector NC-03',
    country: 'Northern Biosphere',
    areaHa: 68000,
    forestCoverPercent: 88,
    recentForestLossPercent: 4.1,
    biodiversityObservationsCount: 410,
    activeAlertsCount: 9,
    climateExposure: 'High',
    environmentalRisk: 'Critical',
    center: { lat: -3.082, lng: -60.115 },
    ecosystemType: 'Dense Submontane Rainforest & Canopy Corridor',
    description: 'Spanning migration paths for primates and apex predators. AI thermal and optical satellites detected new linear clearings and logging roads.',
  },
  {
    id: 'REG-BW04',
    name: 'Blackwood Managed Concession Area',
    sectorCode: 'Sector BW-04',
    country: 'Southern Forestry Zone',
    areaHa: 24000,
    forestCoverPercent: 72,
    recentForestLossPercent: 0.8,
    biodiversityObservationsCount: 88,
    activeAlertsCount: 2,
    climateExposure: 'Low',
    environmentalRisk: 'Moderate',
    center: { lat: -3.210, lng: -60.055 },
    ecosystemType: 'FSC-Certified Selective Harvest Hardwood Forest',
    description: 'Regulated harvest zone. Discrepancy audits between declared sawmill manifests and in-situ acoustic sensors under human review.',
  },
  {
    id: 'REG-RN05',
    name: 'Rio Negro Tributary Headwaters',
    sectorCode: 'Sector RN-05',
    country: 'Western Peatland Biosphere',
    areaHa: 52000,
    forestCoverPercent: 93,
    recentForestLossPercent: 1.7,
    biodiversityObservationsCount: 265,
    activeAlertsCount: 3,
    climateExposure: 'Severe',
    environmentalRisk: 'High',
    center: { lat: -3.140, lng: -60.180 },
    ecosystemType: 'Blackwater Igapó Forest & Peat Soil Matrix',
    description: 'High carbon storage ecosystem sensitive to climate drought anomalies and fire weather indices. Satellite thermal alerts flagged.',
  },
];

export const MOCK_SUPPLIERS_FACILITIES: SupplyChainFacility[] = [
  {
    id: 'FAC-001',
    name: 'Supplier A Timber Processing & Export Hub',
    facilityType: 'Sawmill',
    company: 'Apex Wood Logistics Ltd',
    riskLevel: 'HIGH',
    certificationStatus: 'PENDING_AUDIT',
    coordinates: { lat: -3.195, lng: -59.890 },
    deforestationExposure: '1.8km from Core Nature Reserve buffer; 3 volumetric anomalies logged',
    annualThroughput: '48,000 m³ / yr',
  },
  {
    id: 'FAC-002',
    name: 'Kupari River Log Pond & Barge Depot',
    facilityType: 'Logistics Corridor',
    company: 'Trans-Corridor Shipping Consortium',
    riskLevel: 'HIGH',
    certificationStatus: 'UNVERIFIED',
    coordinates: { lat: -3.185, lng: -59.870 },
    deforestationExposure: 'Waterway transit point flagged for unmanifested nighttime barges',
    annualThroughput: '120,000 m³ / yr',
  },
  {
    id: 'FAC-003',
    name: 'Emerald Valley Agro-Processing Concession',
    facilityType: 'Agricultural Concession',
    company: 'Verdant Agriculture Global',
    riskLevel: 'MEDIUM',
    certificationStatus: 'RSPO_CERTIFIED',
    coordinates: { lat: -3.175, lng: -59.950 },
    deforestationExposure: 'Buffer expansion detected near riparian zone boundary; verification ongoing',
    annualThroughput: '35,000 MT / yr',
  },
  {
    id: 'FAC-004',
    name: 'Northern Alluvial Prospecting Facility',
    facilityType: 'Mining Extraction',
    company: 'Oro Mineral Resources',
    riskLevel: 'CRITICAL',
    certificationStatus: 'UNVERIFIED',
    coordinates: { lat: -3.075, lng: -60.145 },
    deforestationExposure: 'Unlicensed excavator silt runoff detected by optical multispectral satellite',
    annualThroughput: 'Under Investigation',
  },
];

export const MOCK_BIODIVERSITY_RECORDS: BiodiversityRecord[] = [
  {
    id: 'BIO-001',
    species: 'Tapirus bairdii',
    commonName: 'Baird\'s / Lowland Tapir',
    category: 'Mammal',
    observationMethod: 'Camera-Trap',
    conservationStatus: 'Endangered',
    coordinates: { lat: -3.131, lng: -60.018 },
    locationName: 'Tapir Ridge Spring Trail',
    timestamp: '2026-09-24 07:15 UTC',
    count: 2,
  },
  {
    id: 'BIO-002',
    species: 'Panthera onca',
    commonName: 'Jaguar',
    category: 'Mammal',
    observationMethod: 'Camera-Trap',
    conservationStatus: 'Near Threatened',
    coordinates: { lat: -3.090, lng: -60.110 },
    locationName: 'Northern Canopy Wildlife Pass',
    timestamp: '2026-09-23 23:40 UTC',
    count: 1,
  },
  {
    id: 'BIO-003',
    species: 'Harpia harpyja',
    commonName: 'Harpy Eagle Nesting Site',
    category: 'Bird',
    observationMethod: 'Acoustic Sensor',
    conservationStatus: 'Vulnerable',
    coordinates: { lat: -3.118, lng: -60.040 },
    locationName: 'Sector A17 Canopy Tower 4',
    timestamp: '2026-09-24 09:02 UTC',
    count: 1,
  },
  {
    id: 'BIO-004',
    species: 'Buceros bicornis',
    commonName: 'Great Hornbill',
    category: 'Bird',
    observationMethod: 'Acoustic Sensor',
    conservationStatus: 'Vulnerable',
    coordinates: { lat: -3.155, lng: -59.995 },
    locationName: 'Emerald River Old Growth Stand',
    timestamp: '2026-09-24 06:30 UTC',
    count: 4,
  },
  {
    id: 'BIO-005',
    species: 'Manis javanica',
    commonName: 'Sunda Pangolin',
    category: 'Mammal',
    observationMethod: 'Ranger Patrol',
    conservationStatus: 'Critically Endangered',
    coordinates: { lat: -3.238, lng: -59.930 },
    locationName: 'South Slope Sanctuary',
    timestamp: '2026-09-22 14:10 UTC',
    count: 1,
  },
];

export const MOCK_COMPLIANCE_RECORDS: ComplianceRecord[] = [
  {
    id: 'CMP-001',
    permitNumber: 'PERMIT-MM-TMB-2026-9041',
    holder: 'Supplier A / Apex Wood Logistics',
    permitType: 'Timber Concession',
    status: 'Discrepancy Detected',
    coordinates: { lat: -3.195, lng: -59.890 },
    locationName: 'Kupari Border Sector',
    areaAuthorizedHa: 450,
    inconsistencySummary: 'Manifest declares 18m³ Teak; acoustic and volumetric weighbridge detected 42m³ Rosewood mix.',
  },
  {
    id: 'CMP-002',
    permitNumber: 'LIC-LC-2026-081',
    holder: 'Verdant Agriculture Global',
    permitType: 'Land Clearing',
    status: 'Discrepancy Detected',
    coordinates: { lat: -3.175, lng: -59.950 },
    locationName: 'Emerald River Corridor',
    areaAuthorizedHa: 200,
    inconsistencySummary: 'Clearing activity extends 1.4 km beyond authorized boundary polygon into protected buffer.',
  },
  {
    id: 'CMP-003',
    permitNumber: 'CON-MIN-2025-014',
    holder: 'Oro Mineral Resources',
    permitType: 'Mineral Extraction',
    status: 'Missing Documentation',
    coordinates: { lat: -3.075, lng: -60.145 },
    locationName: 'Northern Canopy Corridor',
    areaAuthorizedHa: 80,
    inconsistencySummary: 'Environmental impact mitigation certificate expired; heavy dredging equipment operating without active permit.',
  },
];

// 150 Cameras (Generated & Seeded)
export const MOCK_CAMERAS: CameraFeed[] = Array.from({ length: 150 }, (_, i) => {
  const idNum = (i + 1).toString().padStart(3, '0');
  const zone = FOREST_ZONES[i % FOREST_ZONES.length];
  const isOnline = i % 18 !== 0;
  const isNight = false;
  const labels = ['Vehicle (Pickup)', 'Truck (Flatbed)', 'Chainsaw Equipment', 'Excavator / Heavy Machinery', 'Person (Unauthorized)', 'Smoke Plume', 'Log Pile', 'Normal Wildlife'];
  const activeLabel = labels[i % labels.length];

  return {
    id: `DEV-CAM-${idNum}`,
    name: `Camera CAM-${idNum} (${zone.name.split(' ')[0]})`,
    type: i % 4 === 0 ? 'THERMAL_CAMERA' : 'AI_CAMERA',
    zone: zone.name,
    coordinates: {
      lat: zone.center.lat + (Math.sin(i * 1.3) * 0.04),
      lng: zone.center.lng + (Math.cos(i * 1.3) * 0.04),
    },
    batteryPercent: Math.max(18, Math.floor(100 - (i * 2.3) % 85)),
    solarChargingRate: isOnline ? 18.4 + (i % 6) : 0,
    signalStrength: isOnline ? 85 - (i % 20) : 0,
    networkType: i % 3 === 0 ? 'Starlink-Mesh' : 'LTE-M',
    firmwareVersion: 'v4.2.1-edge-vision',
    lastHeartbeat: isOnline ? 'Just now' : '14m ago',
    temperatureC: 28.5 + (i % 4),
    storageUsedPercent: 42 + (i % 38),
    status: isOnline ? (i % 12 === 0 ? 'LOW_BATTERY' : 'ONLINE') : 'OFFLINE',
    installedDate: '2025-04-12',
    lastMaintenanceDate: '2026-08-10',
    uptimePercent: 98.4,
    streamUrl: `https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=640&auto=format&fit=crop&q=80`,
    resolution: '4K UltraHD 60fps',
    fps: 30,
    nightVisionActive: isNight,
    thermalMode: i % 4 === 0,
    recentDetections: [
      {
        label: activeLabel,
        confidence: 84 + (i % 14),
        timestamp: '10:14:22',
        bbox: [0.25, 0.35, 0.45, 0.5],
      },
    ],
  };
});

// 300 IoT Sensors (Acoustics, Smoke, Thermal, GPS, LoRaWAN)
export const MOCK_DEVICES: Device[] = Array.from({ length: 300 }, (_, i) => {
  const idNum = (i + 1).toString().padStart(3, '0');
  const zone = FOREST_ZONES[i % FOREST_ZONES.length];
  const types: Device['type'][] = [
    'ACOUSTIC_SENSOR',
    'SMOKE_SENSOR',
    'TEMPERATURE_SENSOR',
    'HUMIDITY_SENSOR',
    'MOTION_SENSOR',
    'GPS_DEVICE',
    'ENVIRONMENTAL_SENSOR',
    'EDGE_AI_DEVICE',
  ];
  const type = types[i % types.length];
  const isOnline = i % 25 !== 0;

  return {
    id: `DEV-IOT-${idNum}`,
    name: `${type.replace(/_/g, ' ')} #${idNum}`,
    type,
    zone: zone.name,
    coordinates: {
      lat: zone.center.lat + (Math.sin(i * 0.9) * 0.05),
      lng: zone.center.lng + (Math.cos(i * 0.9) * 0.05),
    },
    batteryPercent: Math.max(12, Math.floor(100 - (i * 1.8) % 88)),
    solarChargingRate: isOnline ? 12.0 + (i % 8) : 0,
    signalStrength: isOnline ? 92 - (i % 25) : 0,
    networkType: i % 2 === 0 ? 'LoRaWAN' : 'Starlink-Mesh',
    firmwareVersion: 'v2.8.0-acoustic-mesh',
    lastHeartbeat: isOnline ? '30s ago' : '45m ago',
    temperatureC: 27.2 + (i % 6),
    storageUsedPercent: 35 + (i % 45),
    status: isOnline ? (i % 14 === 0 ? 'LOW_BATTERY' : 'ONLINE') : (i % 50 === 0 ? 'TAMPER_ALERT' : 'OFFLINE'),
    installedDate: '2025-06-15',
    lastMaintenanceDate: '2026-07-22',
    uptimePercent: 99.1,
    currentReading: type === 'ACOUSTIC_SENSOR' ? '42 dB (Normal Ambient)' : type === 'SMOKE_SENSOR' ? '0.02 ppm CO' : '28.4°C / 84% RH',
  };
});

// Acoustic sensor readings with sample waveforms
export const MOCK_ACOUSTIC_READINGS: AcousticSensorReading[] = [
  {
    sensorId: 'DEV-IOT-014',
    sensorName: 'Acoustic Triangulator A-204',
    zone: 'Tapir Ridge Strict Nature Reserve',
    coordinates: { lat: -3.128, lng: -60.031 },
    timestamp: '2026-09-24 10:14:08 UTC',
    classification: 'CHAINSAW_LIKE_SOUND',
    confidence: 89,
    decibels: 78.4,
    durationSeconds: 142,
    waveformSample: [12, 18, 45, 88, 92, 76, 85, 94, 60, 42, 85, 96, 91, 74, 40, 15, 22, 54, 82, 95],
    frequencyPeakHz: 2850,
    status: 'CONFIRMED_ANOMALY',
  },
  {
    sensorId: 'DEV-IOT-042',
    sensorName: 'Acoustic Node Alpha-09',
    zone: 'Northern Canopy Wildlife Corridor',
    coordinates: { lat: -3.085, lng: -60.118 },
    timestamp: '2026-09-24 09:48:32 UTC',
    classification: 'HEAVY_MACHINERY',
    confidence: 86,
    decibels: 72.1,
    durationSeconds: 310,
    waveformSample: [30, 45, 55, 62, 70, 75, 78, 80, 75, 72, 68, 65, 70, 74, 76, 70, 58, 45, 32, 25],
    frequencyPeakHz: 480,
    status: 'CONFIRMED_ANOMALY',
  },
  {
    sensorId: 'DEV-IOT-108',
    sensorName: 'Acoustic Perimeter B-12',
    zone: 'Emerald River Corridor',
    coordinates: { lat: -3.168, lng: -59.980 },
    timestamp: '2026-09-24 08:31:15 UTC',
    classification: 'VEHICLE_ENGINE',
    confidence: 91,
    decibels: 68.9,
    durationSeconds: 95,
    waveformSample: [10, 20, 35, 50, 65, 72, 68, 55, 48, 60, 65, 58, 45, 38, 25, 18, 12, 8, 5, 2],
    frequencyPeakHz: 120,
    status: 'CONFIRMED_ANOMALY',
  },
  {
    sensorId: 'DEV-IOT-188',
    sensorName: 'Canopy Soundscape Node 88',
    zone: 'Tapir Ridge Strict Nature Reserve',
    coordinates: { lat: -3.132, lng: -60.019 },
    timestamp: '2026-09-24 07:12:00 UTC',
    classification: 'EXPLOSION_OR_GUNSHOT',
    confidence: 82,
    decibels: 92.6,
    durationSeconds: 4,
    waveformSample: [5, 8, 98, 95, 82, 60, 40, 25, 15, 10, 8, 5, 4, 3, 2, 2, 1, 1, 0, 0],
    frequencyPeakHz: 4200,
    status: 'PENDING_ANALYSIS',
  },
];

// 40 Incidents with rich AI explanations and evidence
export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'ENV-2026-000182',
    type: 'ILLEGAL_DEFORESTATION',
    title: 'Correlated Mechanical Clearing & Chainsaw Activity in Core Reserve',
    severity: 'CRITICAL',
    status: 'UNDER_REVIEW',
    locationName: 'Tapir Ridge Strict Nature Reserve - Sector 4B',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1254, lng: -60.0248 },
    timestamp: '2026-09-24 02:18:00 UTC',
    detectionSources: [
      'Acoustic Sensor A-204 (Chainsaw Signature)',
      'Camera CAM-041 (Heavy Machinery / Flatbed Truck)',
      'Sentinel-2 Satellite (NDVI drop 34%)',
      'Permit Database (No valid logging concession)',
    ],
    aiConfidence: 91,
    riskLevel: 'CRITICAL',
    aiExplanation: {
      whatDetected: 'Chainsaw acoustic frequency (2.85 kHz) correlated with heavy diesel logging tractor and flatbed vehicle detection inside a strictly forbidden Core Conservation Area.',
      whereDetected: 'Tapir Ridge Strict Nature Reserve (Lat: -3.1254, Lng: -60.0248), 14.2 km inside strict non-extraction perimeter.',
      whenDetected: '2026-09-24 between 02:14 UTC and 02:35 UTC (nighttime activity).',
      source: 'Multi-Sensor Fusion (Acoustic A-204, Optical Camera CAM-041, Satellite Sentinel-2, Registry Crosscheck).',
      aiConfidence: 91,
      supportingSignals: [
        'Acoustic Sensor A-204 logged continuous chainsaw-like harmonic signature for 142 seconds at 78.4 dB.',
        'Thermal Camera CAM-041 identified heavy vehicle engine exhaust thermal bloom at 02:18 UTC.',
        'Sentinel-2 MSI surface reflectance delta indicates 4.8 ha canopy opening since last cloud-free pass (3 days ago).',
        'National Concession Registry contains NO valid timber harvesting concession or road access permit for this coordinate.',
      ],
      contradictingSignals: [
        'Forest Ranger Patrol Team Delta was operating 6.8 km East earlier in the evening (verified as non-correlated).',
      ],
      whyFlagged: [
        'Nighttime operation (02:18 UTC) in strict nature reserve prohibits all vehicular or mechanical logging.',
        'Acoustic and optical signals confirmed within 4 minutes of each other at identical radial bearing.',
        'High probability of ongoing extraction of protected hardwood (Ipê / Rosewood species).',
      ],
      whatHumanReviewShouldCheck: [
        'Inspect Camera CAM-041 high-resolution night capture for license plate or marking numbers.',
        'Verify if any emergency scientific research expedition or indigenous fire mitigation was pre-cleared.',
        'Dispatch Field Ranger Patrol Team Beta for rapid interdiction and on-site coordinates verification.',
      ],
      disclaimer: 'IMPORTANT NOTICE: AI detects, correlates, and assists. Authorized forest protection authorities must verify physical facts and determine legal violations before consequential enforcement action is undertaken.',
    },
    relatedDeviceIds: ['DEV-CAM-041', 'DEV-IOT-014', 'DEV-IOT-015'],
    relatedCameraIds: ['DEV-CAM-041'],
    relatedVehiclePlate: 'AMZ-8894 (Suspect Flatbed)',
    evidenceIds: ['EVD-2026-00412', 'EVD-2026-00413', 'EVD-2026-00414', 'EVD-2026-00415'],
    assignedInvestigator: 'Inspector Marcus Reed',
    assignedOfficerBadge: 'FG-INV-44',
    reviewerNotes: 'Awaiting visual review of CAM-041 video clip. Field Team Bravo has been placed on alert status at Ranger Outpost 3.',
    satelliteEvidence: {
      beforeDate: '2026-09-18',
      afterDate: '2026-09-23',
      hectaresAffected: 4.8,
      ndviDropPercent: 34,
      beforeThumb: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&auto=format&fit=crop&q=80',
      afterThumb: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&auto=format&fit=crop&q=80',
    },
    timeline: [
      { time: '02:14:02 UTC', action: 'Acoustic detection of 2.85 kHz chainsaw frequency', actor: 'Acoustic Node A-204 (AI)' },
      { time: '02:18:15 UTC', action: 'Optical camera CAM-041 detects heavy vehicle incursion', actor: 'CAM-041 Edge Vision (AI)' },
      { time: '02:20:00 UTC', action: 'Correlation Engine generates Incident ENV-2026-000182 with 91% confidence', actor: 'FORESTGUARD Correlation AI' },
      { time: '02:22:10 UTC', action: 'Automated alert broadcasted to Regional Duty Desk', actor: 'System Notification Service' },
      { time: '02:35:44 UTC', action: 'Duty Officer Vance placed incident in UNDER_REVIEW status', actor: 'Cmdr. Elena Vance' },
    ],
  },
  {
    id: 'ENV-2026-000183',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Discrepancy in Declared vs Scale Timber Weight at Checkpoint Kupari',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Kupari Border Checkpoint Sector (Highway BR-319 Junction)',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1902, lng: -59.8812 },
    timestamp: '2026-09-24 06:45:00 UTC',
    detectionSources: [
      'Checkpoint Weighbridge #2',
      'Volumetric Laser Timber Scanner',
      'Electronic Permit Database SISFLORA',
    ],
    aiConfidence: 96,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Timber transport manifest discrepancy: Declared payload 18.0 m³ of secondary softwoods, but electronic weighbridge recorded 27.4 m³ with high-density hardwood mass profile.',
      whereDetected: 'Kupari Border Transit Checkpoint, Bay 2 (BR-319 km 84).',
      whenDetected: '2026-09-24 at 06:45 UTC.',
      source: 'Automated Weighbridge Telemetry cross-referenced with Timber Transit Permit PMT-2026-4412.',
      aiConfidence: 96,
      supportingSignals: [
        'Electronic weighbridge gross weight: 44,200 kg (expected: 32,800 kg).',
        'Volumetric optical lidar scan calculated 26.8 m³ physical log volume.',
        'Wood density curve indicates Dalbergia nigra (Brazilian Rosewood) or Handroanthus (Ipê), NOT Pinus/Eucalyptus as declared.',
      ],
      contradictingSignals: [],
      whyFlagged: [
        'Volume excess exceeds statutory 5% tolerance threshold by +48.9%.',
        'Species substitution suspected based on volumetric mass coefficient (0.94 g/cm³ vs declared 0.52 g/cm³).',
      ],
      whatHumanReviewShouldCheck: [
        'Perform physical log tagging and bark inspection.',
        'Verify barcode chain of custody on each individual log stump stamp.',
        'Hold transport vehicle pending compliance verification.',
      ],
      disclaimer: 'Discrepancy detection requires human forensic verification before issuance of formal administrative citation or vehicle seizure.',
    },
    relatedDeviceIds: ['DEV-CAM-019', 'DEV-IOT-092'],
    relatedCameraIds: ['DEV-CAM-019'],
    relatedVehiclePlate: 'TRK-9021-BR',
    relatedPermitId: 'PMT-2026-4412',
    assignedInvestigator: 'Inspector Clara Gomes',
    assignedOfficerBadge: 'FG-INV-12',
    evidenceIds: ['EVD-2026-00416', 'EVD-2026-00417'],
    verifiedBy: 'Forest Officer Da Silva (Badge FO-309)',
    verifiedAt: '2026-09-24 07:15 UTC',
    timeline: [
      { time: '06:45 UTC', action: 'Truck scanned at Kupari Checkpoint Bay 2', actor: 'Weighbridge Scanner #2' },
      { time: '06:47 UTC', action: 'Permit discrepancy flagged (+52% volume mass delta)', actor: 'Timber AI Validator' },
      { time: '07:15 UTC', action: 'Officer Da Silva manually verified discrepancy and initiated Vehicle Hold order', actor: 'Forest Officer Da Silva' },
    ],
  },
  {
    id: 'ENV-2026-000184',
    type: 'UNAUTHORIZED_ROAD_CONSTRUCTION',
    title: 'Linear Forest Clearing Anomaly (Suspected Illegal Logging Penetration Road)',
    severity: 'HIGH_PRIORITY',
    status: 'INVESTIGATION',
    locationName: 'Northern Canopy Wildlife Corridor - Sector 2A',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0822, lng: -60.1158 },
    timestamp: '2026-09-23 18:20:00 UTC',
    detectionSources: ['PlanetScope 3m Satellite imagery', 'Acoustic Node Alpha-09', 'Drone Patrol Recon Delta'],
    aiConfidence: 88,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Linear canopy incision spanning 2.4 kilometers with width 8-12 meters penetrating into virgin primary forest from legal concession perimeter.',
      whereDetected: 'Northern Canopy Wildlife Corridor, entering from Concession 4 boundary.',
      whenDetected: '2026-09-23 18:20 UTC.',
      source: 'PlanetScope SkySat Change Algorithm & Aerial Drone Orthomosaic.',
      aiConfidence: 88,
      supportingSignals: [
        'Continuous linear scar advancing at ~350 meters per day.',
        'Bulldozer/excavator acoustic signals logged by Acoustic Node Alpha-09.',
        'Zero environmental impact assessment or road clearance authorization on file with Ministry.',
      ],
      contradictingSignals: [],
      whyFlagged: [
        'Penetration road opens remote biological reserve to uncontrolled illegal poaching and wildcat miners.',
      ],
      whatHumanReviewShouldCheck: [
        'Examine drone high-definition video of the road head.',
        'Check whether adjacent concession holder is encroaching beyond licensed boundary line.',
      ],
      disclaimer: 'Satellite and aerial detections assist field planners and must be confirmed on-site by sworn environmental inspectors.',
    },
    relatedDeviceIds: ['DEV-CAM-088', 'DEV-IOT-042'],
    relatedCameraIds: ['DEV-CAM-088'],
    assignedInvestigator: 'Inspector Marcus Reed',
    assignedOfficerBadge: 'FG-INV-44',
    evidenceIds: ['EVD-2026-00418', 'EVD-2026-00419', 'EVD-2026-00420'],
    timeline: [
      { time: 'Sep 23 18:20 UTC', action: 'Satellite change alert triggered for 2.4 km linear disturbance', actor: 'Satellite AI Service' },
      { time: 'Sep 23 20:00 UTC', action: 'Drone Recon flight deployed to capture oblique 4K footage', actor: 'Pilot Ranger Sato' },
      { time: 'Sep 24 01:10 UTC', action: 'Formal investigation opened (CASE-2026-0089)', actor: 'Lead Inv. Marcus Reed' },
    ],
  },
  {
    id: 'ENV-2026-000185',
    type: 'FIRE_SMOKE_ANOMALY',
    title: 'Thermal Hotspot & Particulate Spike near Peatland Buffer',
    severity: 'SUSPICIOUS',
    status: 'UNDER_REVIEW',
    locationName: 'Rio Negro Tributary Headwaters',
    zoneId: 'ZN-05',
    coordinates: { lat: -3.1415, lng: -60.1804 },
    timestamp: '2026-09-24 08:50:00 UTC',
    detectionSources: ['VIIRS Active Fire Product', 'Smoke Sensor DEV-IOT-212', 'Thermal Drone Feed'],
    aiConfidence: 84,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Thermal anomaly of 312 Kelvin detected in conjunction with PM2.5 spike (145 ug/m³) and CO increase.',
      whereDetected: 'Rio Negro Tributary Headwaters, 3.1 km North of seasonal marshland.',
      whenDetected: '2026-09-24 08:50 UTC.',
      source: 'VIIRS Suomi-NPP Hotspot & Ground Smoke Sensor.',
      aiConfidence: 84,
      supportingSignals: ['Ground sensor logged 4x rise in carbon monoxide over baseline.'],
      contradictingSignals: ['Lightning strikes logged in vicinity during previous night rain shower.'],
      whyFlagged: ['Potential early-stage agricultural burn or smoldering ground fire.'],
      whatHumanReviewShouldCheck: ['Assess if natural lightning fire or intentional agricultural land-clearing burn.'],
      disclaimer: 'Thermal predictions provide early warning and require meteorological and human ground validation.',
    },
    relatedDeviceIds: ['DEV-IOT-212'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00421'],
    timeline: [
      { time: '08:50 UTC', action: 'Thermal hotspot matched with ground smoke sensor trigger', actor: 'Thermal Sensor Hub' },
    ],
  },
  {
    id: 'ENV-2026-000186',
    type: 'UNAUTHORIZED_ENTRY_RESTRICTED_ZONE',
    title: 'Barge Movement Detected with Heavy Extraction Machinery on Emerald River',
    severity: 'HIGH_PRIORITY',
    status: 'DETECTED',
    locationName: 'Emerald River Corridor - River Mile 42',
    zoneId: 'ZN-02',
    coordinates: { lat: -3.1652, lng: -59.9824 },
    timestamp: '2026-09-24 09:12:00 UTC',
    detectionSources: ['River Camera CAM-019', 'Acoustic Hydrophone HYD-04'],
    aiConfidence: 87,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Unregistered river push-barge carrying caterpillar excavator and fuel drums navigating upstream into closed protected riparian zone.',
      whereDetected: 'Emerald River Corridor, River Mile 42.',
      whenDetected: '2026-09-24 09:12 UTC.',
      source: 'CCTV Stream CAM-019 & Hydrophone HYD-04.',
      aiConfidence: 87,
      supportingSignals: [
        'AIS transponder silent (no commercial or authorized vessel signal).',
        'Hydrophone confirms twin heavy low-speed diesel propulsion signature.',
      ],
      contradictingSignals: [],
      whyFlagged: ['No river navigation permit issued for commercial equipment beyond River Mile 35.'],
      whatHumanReviewShouldCheck: ['River patrol boat intercept at River Narrows Checkpoint.'],
      disclaimer: 'Vessel identification based on automated optical stream requires visual confirmation by river police.',
    },
    relatedDeviceIds: ['DEV-CAM-019'],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00422'],
    timeline: [
      { time: '09:12 UTC', action: 'Automated object detection classified barge + excavator', actor: 'Camera CAM-019 Edge' },
    ],
  },
  // --- Historical Incidents for Geospatial Heatmap & Temporal Analysis (30-day window) ---
  // Cluster A: Tapir Ridge Strict Reserve (High Deforestation Hot Zone)
  {
    id: 'ENV-2026-000179',
    type: 'ACOUSTIC_CHAINSAW_ACTIVITY',
    title: 'Nighttime Chainsaw Signature Spike (Tapir Ridge Sector 4B)',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Sector 4B',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1272, lng: -60.0261 },
    timestamp: '2026-09-21 23:45:00 UTC',
    detectionSources: ['Acoustic Sensor A-204', 'Acoustic Node Alpha-07'],
    aiConfidence: 89,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Repetitive chainsaw harmonic pulses logged over 180 seconds.',
      whereDetected: 'Tapir Ridge Sector 4B.',
      whenDetected: '2026-09-21 23:45 UTC.',
      source: 'Acoustic Node A-204.',
      aiConfidence: 89,
      supportingSignals: ['Continuous 2.8 kHz acoustic profile matching two-stroke logging saw.'],
      contradictingSignals: [],
      whyFlagged: ['Strict Reserve core zone with zero permit activity.'],
      whatHumanReviewShouldCheck: ['Ranger night dispatch.'],
      disclaimer: 'Verification required before enforcement.',
    },
    relatedDeviceIds: ['DEV-IOT-014'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00401'],
    timeline: [{ time: '23:45 UTC', action: 'Acoustic detection logged', actor: 'A-204' }],
  },
  {
    id: 'ENV-2026-000175',
    type: 'ILLEGAL_DEFORESTATION',
    title: 'Satellite Multispectral Canopy Loss (Tapir Ridge Core)',
    severity: 'CRITICAL',
    status: 'INVESTIGATION',
    locationName: 'Tapir Ridge Strict Nature Reserve - Core Zone',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1235, lng: -60.0225 },
    timestamp: '2026-09-18 14:10:00 UTC',
    detectionSources: ['Sentinel-2 L2A MSI', 'PlanetScope 3m'],
    aiConfidence: 94,
    riskLevel: 'CRITICAL',
    aiExplanation: {
      whatDetected: '2.1 hectare clear-cut canopy opening confirmed by multispectral NDVI index drop.',
      whereDetected: 'Tapir Ridge Core Reserve Sector 4.',
      whenDetected: '2026-09-18 14:10 UTC.',
      source: 'Sentinel-2 automated change detection.',
      aiConfidence: 94,
      supportingSignals: ['NDVI fell from 0.82 to 0.41 over 5 day interval.'],
      contradictingSignals: [],
      whyFlagged: ['High value ancient hardwood extraction patch.'],
      whatHumanReviewShouldCheck: ['Cross-reference drone orthophoto.'],
      disclaimer: 'Satellite canopy analysis.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: ['DEV-CAM-041'],
    evidenceIds: ['EVD-2026-00392'],
    timeline: [{ time: '14:10 UTC', action: 'Satellite delta alert processed', actor: 'Copernicus Hub' }],
  },
  {
    id: 'ENV-2026-000171',
    type: 'HEAVY_MACHINERY_ENCROACHMENT',
    title: 'Diesel Crawler Tractor Incursion near Access Trail Delta',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Trail Delta',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1285, lng: -60.0289 },
    timestamp: '2026-09-15 03:20:00 UTC',
    detectionSources: ['Seismic Ground Sensor S-02', 'Acoustic Node Alpha-07'],
    aiConfidence: 87,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Low-frequency seismic rumble and diesel engine harmonic detected.',
      whereDetected: 'Access Trail Delta entrance.',
      whenDetected: '2026-09-15 03:20 UTC.',
      source: 'Seismic & Acoustic fusion.',
      aiConfidence: 87,
      supportingSignals: ['Heavy track vibration profile.'],
      contradictingSignals: [],
      whyFlagged: ['Unauthorized tracked machine entering restricted zone.'],
      whatHumanReviewShouldCheck: ['Inspect ground tracks and barrier.'],
      disclaimer: 'Seismic classification.',
    },
    relatedDeviceIds: ['DEV-IOT-015'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00381'],
    timeline: [{ time: '03:20 UTC', action: 'Seismic surge registered', actor: 'S-02' }],
  },
  {
    id: 'ENV-2026-000168',
    type: 'ACOUSTIC_CHAINSAW_ACTIVITY',
    title: 'Intermittent Logging Activity in Tapir Ridge Western Buffer',
    severity: 'SUSPICIOUS',
    status: 'VERIFIED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Western Sector',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1310, lng: -60.0330 },
    timestamp: '2026-09-12 11:30:00 UTC',
    detectionSources: ['Canopy Soundscape Node 88'],
    aiConfidence: 81,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Intermittent high-frequency mechanical cuts.',
      whereDetected: 'Tapir Ridge Western boundary.',
      whenDetected: '2026-09-12 11:30 UTC.',
      source: 'Soundscape Node 88.',
      aiConfidence: 81,
      supportingSignals: ['Harmonic matches standard portable logger saw.'],
      contradictingSignals: [],
      whyFlagged: ['Buffer zone boundary encroachment.'],
      whatHumanReviewShouldCheck: ['Verify permit boundaries.'],
      disclaimer: 'Automated audio detection.',
    },
    relatedDeviceIds: ['DEV-IOT-188'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00370'],
    timeline: [{ time: '11:30 UTC', action: 'Audio flagged by AI', actor: 'Node 88' }],
  },
  {
    id: 'ENV-2026-000164',
    type: 'ILLEGAL_DEFORESTATION',
    title: 'Under-Canopy Clearing Detected by Aerial Lidar',
    severity: 'HIGH_PRIORITY',
    status: 'INVESTIGATION',
    locationName: 'Tapir Ridge Strict Nature Reserve - Sector 4A',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1240, lng: -60.0210 },
    timestamp: '2026-09-08 16:45:00 UTC',
    detectionSources: ['Aerial Drone Recon Delta', 'Lidar Point Cloud'],
    aiConfidence: 92,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Selective felling of 18 mature emergent trees beneath upper canopy.',
      whereDetected: 'Sector 4A ancient grove.',
      whenDetected: '2026-09-08 16:45 UTC.',
      source: 'Drone Lidar canopy penetration survey.',
      aiConfidence: 92,
      supportingSignals: ['Sub-canopy structure disruption.'],
      contradictingSignals: [],
      whyFlagged: ['High value Rosewood target.'],
      whatHumanReviewShouldCheck: ['Field patrol physical tag survey.'],
      disclaimer: 'Lidar survey analysis.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00362'],
    timeline: [{ time: '16:45 UTC', action: 'Lidar processing completed', actor: 'Drone GIS' }],
  },
  {
    id: 'ENV-2026-000160',
    type: 'UNAUTHORIZED_ENTRY_RESTRICTED_ZONE',
    title: 'Nighttime Off-Road Vehicle Incursion (Tapir Sector 4)',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Southern Access',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1360, lng: -60.0270 },
    timestamp: '2026-09-05 01:15:00 UTC',
    detectionSources: ['Thermal Camera CAM-038', 'Motion Sensor PIR-12'],
    aiConfidence: 83,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Unlit 4x4 pickup navigating unpaved boundary path.',
      whereDetected: 'Tapir Ridge Southern Access.',
      whenDetected: '2026-09-05 01:15 UTC.',
      source: 'PIR motion & Thermal camera.',
      aiConfidence: 83,
      supportingSignals: ['Exhaust thermal signature.'],
      contradictingSignals: [],
      whyFlagged: ['No night driving permitted.'],
      whatHumanReviewShouldCheck: ['Patrol log.'],
      disclaimer: 'Thermal optical AI.',
    },
    relatedDeviceIds: ['DEV-CAM-038'],
    relatedCameraIds: ['DEV-CAM-038'],
    evidenceIds: ['EVD-2026-00350'],
    timeline: [{ time: '01:15 UTC', action: 'Motion alert', actor: 'PIR-12' }],
  },
  {
    id: 'ENV-2026-000155',
    type: 'ACOUSTIC_CHAINSAW_ACTIVITY',
    title: 'Early Chainsaw Harmonic Activity (Tapir Ridge Sector 4B)',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Sector 4B',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1265, lng: -60.0240 },
    timestamp: '2026-09-02 10:20:00 UTC',
    detectionSources: ['Acoustic Sensor A-204'],
    aiConfidence: 79,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Short burst chainsaw audio signature (45 seconds).',
      whereDetected: 'Sector 4B.',
      whenDetected: '2026-09-02 10:20 UTC.',
      source: 'Sensor A-204.',
      aiConfidence: 79,
      supportingSignals: ['2.85 kHz harmonic.'],
      contradictingSignals: [],
      whyFlagged: ['Core nature reserve zone.'],
      whatHumanReviewShouldCheck: ['Field reconnaissance.'],
      disclaimer: 'Automated detection.',
    },
    relatedDeviceIds: ['DEV-IOT-014'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00335'],
    timeline: [{ time: '10:20 UTC', action: 'Audio trigger', actor: 'A-204' }],
  },
  {
    id: 'ENV-2026-000149',
    type: 'UNAUTHORIZED_ENTRY_RESTRICTED_ZONE',
    title: 'Foot Patrol Intrusion on Unmapped Footpath',
    severity: 'INFORMATIONAL',
    status: 'CLOSED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Sector 3',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1290, lng: -60.0215 },
    timestamp: '2026-08-30 08:40:00 UTC',
    detectionSources: ['PIR Motion Sensor MS-09'],
    aiConfidence: 76,
    riskLevel: 'LOW',
    aiExplanation: {
      whatDetected: 'Human foot traffic on wild animal trail.',
      whereDetected: 'Sector 3 interior.',
      whenDetected: '2026-08-30 08:40 UTC.',
      source: 'PIR motion.',
      aiConfidence: 76,
      supportingSignals: ['PIR signature.'],
      contradictingSignals: [],
      whyFlagged: ['Restricted core zone.'],
      whatHumanReviewShouldCheck: ['Review trail camera.'],
      disclaimer: 'PIR sensor trigger.',
    },
    relatedDeviceIds: ['DEV-IOT-009'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00318'],
    timeline: [{ time: '08:40 UTC', action: 'PIR logged', actor: 'MS-09' }],
  },
  {
    id: 'ENV-2026-000145',
    type: 'ACOUSTIC_CHAINSAW_ACTIVITY',
    title: 'Canopy Sound Anomaly: Isolated Chainsaw revving',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Tapir Ridge Strict Nature Reserve - Sector 4B',
    zoneId: 'ZN-01',
    coordinates: { lat: -3.1245, lng: -60.0255 },
    timestamp: '2026-08-27 15:10:00 UTC',
    detectionSources: ['Acoustic Sensor A-204'],
    aiConfidence: 82,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Single burst chainsaw audio pattern.',
      whereDetected: 'Tapir Ridge Sector 4B.',
      whenDetected: '2026-08-27 15:10 UTC.',
      source: 'Sensor A-204.',
      aiConfidence: 82,
      supportingSignals: ['Frequency peak at 2.85 kHz.'],
      contradictingSignals: [],
      whyFlagged: ['Core nature reserve zone.'],
      whatHumanReviewShouldCheck: ['Log for pattern tracking.'],
      disclaimer: 'Acoustic detection.',
    },
    relatedDeviceIds: ['DEV-IOT-014'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00305'],
    timeline: [{ time: '15:10 UTC', action: 'Detection logged', actor: 'A-204' }],
  },

  // Cluster B: Northern Canopy Wildlife Corridor (Illegal Road Construction Hot Zone)
  {
    id: 'ENV-2026-000180',
    type: 'UNAUTHORIZED_ROAD_CONSTRUCTION',
    title: 'Linear Clearing Progression: Road Segment Reaching 2.1km',
    severity: 'HIGH_PRIORITY',
    status: 'INVESTIGATION',
    locationName: 'Northern Canopy Wildlife Corridor - Sector 2A',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0835, lng: -60.1170 },
    timestamp: '2026-09-22 17:00:00 UTC',
    detectionSources: ['PlanetScope Satellite', 'Drone Recon'],
    aiConfidence: 91,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Additional 350m linear road cut excavated toward virgin canopy core.',
      whereDetected: 'Northern Corridor Sector 2A.',
      whenDetected: '2026-09-22 17:00 UTC.',
      source: 'Daily Satellite Change detection.',
      aiConfidence: 91,
      supportingSignals: ['Linear soil reflectance scar.'],
      contradictingSignals: [],
      whyFlagged: ['Habitat fragmentation in primary biological corridor.'],
      whatHumanReviewShouldCheck: ['Dispatch interdiction unit.'],
      disclaimer: 'Satellite imagery interpretation.',
    },
    relatedDeviceIds: ['DEV-IOT-042'],
    relatedCameraIds: ['DEV-CAM-088'],
    evidenceIds: ['EVD-2026-00405'],
    timeline: [{ time: '17:00 UTC', action: 'Daily satellite pass analyzed', actor: 'PlanetScope AI' }],
  },
  {
    id: 'ENV-2026-000176',
    type: 'HEAVY_MACHINERY_ENCROACHMENT',
    title: 'Heavy Bulldozer Acoustic Rumble (Northern Canopy)',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Northern Canopy Wildlife Corridor - Sector 2B',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0810, lng: -60.1140 },
    timestamp: '2026-09-19 09:30:00 UTC',
    detectionSources: ['Acoustic Node Alpha-09'],
    aiConfidence: 86,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Low-frequency diesel earthmoving acoustic resonance (480 Hz).',
      whereDetected: 'Northern Canopy road penetration head.',
      whenDetected: '2026-09-19 09:30 UTC.',
      source: 'Node Alpha-09.',
      aiConfidence: 86,
      supportingSignals: ['72 dB heavy machinery spectrum.'],
      contradictingSignals: [],
      whyFlagged: ['Illegal earthmoving inside wildlife corridor.'],
      whatHumanReviewShouldCheck: ['Audio spectrum verification.'],
      disclaimer: 'Acoustic classification.',
    },
    relatedDeviceIds: ['DEV-IOT-042'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00395'],
    timeline: [{ time: '09:30 UTC', action: 'Acoustic engine flag', actor: 'Alpha-09' }],
  },
  {
    id: 'ENV-2026-000170',
    type: 'ILLEGAL_DEFORESTATION',
    title: 'Clandestine Log Staging Deck Identified by Drone',
    severity: 'HIGH_PRIORITY',
    status: 'INVESTIGATION',
    locationName: 'Northern Canopy Wildlife Corridor - Spur 3',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0845, lng: -60.1190 },
    timestamp: '2026-09-14 15:20:00 UTC',
    detectionSources: ['Drone Patrol Recon Delta', 'Optical AI'],
    aiConfidence: 93,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Circular clearing with stacked logs (est. 120 cubic meters) along new road.',
      whereDetected: 'Northern Corridor Spur 3.',
      whenDetected: '2026-09-14 15:20 UTC.',
      source: 'Drone 4K aerial stream.',
      aiConfidence: 93,
      supportingSignals: ['High resolution log stack detection.'],
      contradictingSignals: [],
      whyFlagged: ['Commercial log consolidation point in non-harvest zone.'],
      whatHumanReviewShouldCheck: ['Inspect timber tags.'],
      disclaimer: 'Visual reconnaissance.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: ['DEV-CAM-088'],
    evidenceIds: ['EVD-2026-00378'],
    timeline: [{ time: '15:20 UTC', action: 'Log deck identified by drone', actor: 'Pilot Sato' }],
  },
  {
    id: 'ENV-2026-000166',
    type: 'UNAUTHORIZED_ROAD_CONSTRUCTION',
    title: 'Linear Disturbance Advancing Past Concession Boundary',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Northern Canopy Wildlife Corridor - Sector 2A',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0805, lng: -60.1120 },
    timestamp: '2026-09-11 13:45:00 UTC',
    detectionSources: ['Sentinel-2 L2A', 'Forest Concession Boundary GIS'],
    aiConfidence: 89,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Road head breaches boundary line of Concession 4 into protected corridor.',
      whereDetected: 'Corridor boundary coordinate.',
      whenDetected: '2026-09-11 13:45 UTC.',
      source: 'Satellite GIS overlay.',
      aiConfidence: 89,
      supportingSignals: ['Cross-boundary linear gap.'],
      contradictingSignals: [],
      whyFlagged: ['Direct encroachment from licensed concession.'],
      whatHumanReviewShouldCheck: ['Concession boundary survey.'],
      disclaimer: 'GIS boundary automated alert.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00366'],
    timeline: [{ time: '13:45 UTC', action: 'Boundary violation triggered', actor: 'GIS Engine' }],
  },
  {
    id: 'ENV-2026-000162',
    type: 'HEAVY_MACHINERY_ENCROACHMENT',
    title: 'Excavator and Grader Track Activity (Northern Canopy)',
    severity: 'SUSPICIOUS',
    status: 'VERIFIED',
    locationName: 'Northern Canopy Wildlife Corridor - Concession Border',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0785, lng: -60.1090 },
    timestamp: '2026-09-07 10:15:00 UTC',
    detectionSources: ['Camera CAM-088', 'Acoustic Node Alpha-09'],
    aiConfidence: 84,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Tracked earthmoving equipment operating outside permitted working hours.',
      whereDetected: 'Concession border sector.',
      whenDetected: '2026-09-07 10:15 UTC.',
      source: 'Camera CAM-088.',
      aiConfidence: 84,
      supportingSignals: ['Heavy machinery classified.'],
      contradictingSignals: [],
      whyFlagged: ['Unapproved access path clearing.'],
      whatHumanReviewShouldCheck: ['Permit verification.'],
      disclaimer: 'Optical edge model.',
    },
    relatedDeviceIds: ['DEV-CAM-088'],
    relatedCameraIds: ['DEV-CAM-088'],
    evidenceIds: ['EVD-2026-00355'],
    timeline: [{ time: '10:15 UTC', action: 'Vehicle classified', actor: 'CAM-088' }],
  },
  {
    id: 'ENV-2026-000158',
    type: 'UNAUTHORIZED_ROAD_CONSTRUCTION',
    title: 'Initial Trail Widening & Bulldozer Ground Disturbance',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Northern Canopy Wildlife Corridor - Outer Border',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0760, lng: -60.1060 },
    timestamp: '2026-09-04 14:00:00 UTC',
    detectionSources: ['SkySat Imagery', 'Acoustic Sensor'],
    aiConfidence: 80,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: '6-meter-wide clearing initiated along historical surveyor track.',
      whereDetected: 'Northern Corridor Outer Border.',
      whenDetected: '2026-09-04 14:00 UTC.',
      source: 'SkySat 50cm imagery.',
      aiConfidence: 80,
      supportingSignals: ['Vegetation clearing.'],
      contradictingSignals: [],
      whyFlagged: ['No road concession permit.'],
      whatHumanReviewShouldCheck: ['Check engineering permits.'],
      disclaimer: 'High resolution optical.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00342'],
    timeline: [{ time: '14:00 UTC', action: 'SkySat tasking result', actor: 'Satellite Service' }],
  },
  {
    id: 'ENV-2026-000152',
    type: 'ACOUSTIC_CHAINSAW_ACTIVITY',
    title: 'Multiple Chainsaw Harmonics near Northern Corridor Entrance',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Northern Canopy Wildlife Corridor - Sector 1',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0790, lng: -60.1110 },
    timestamp: '2026-09-01 11:10:00 UTC',
    detectionSources: ['Acoustic Node Alpha-09'],
    aiConfidence: 78,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Chainsaw sound frequency registered.',
      whereDetected: 'Sector 1 boundary.',
      whenDetected: '2026-09-01 11:10 UTC.',
      source: 'Node Alpha-09.',
      aiConfidence: 78,
      supportingSignals: ['2.7 kHz acoustic peak.'],
      contradictingSignals: [],
      whyFlagged: ['Near reserve perimeter.'],
      whatHumanReviewShouldCheck: ['Routine ranger check.'],
      disclaimer: 'Acoustic sensor trigger.',
    },
    relatedDeviceIds: ['DEV-IOT-042'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00325'],
    timeline: [{ time: '11:10 UTC', action: 'Audio flag', actor: 'Alpha-09' }],
  },
  {
    id: 'ENV-2026-000146',
    type: 'HEAVY_MACHINERY_ENCROACHMENT',
    title: 'Excavator Acoustic Rumble (Northern Buffer)',
    severity: 'INFORMATIONAL',
    status: 'CLOSED',
    locationName: 'Northern Canopy Wildlife Corridor - Buffer',
    zoneId: 'ZN-03',
    coordinates: { lat: -3.0740, lng: -60.1030 },
    timestamp: '2026-08-28 09:20:00 UTC',
    detectionSources: ['Acoustic Node Alpha-09'],
    aiConfidence: 75,
    riskLevel: 'LOW',
    aiExplanation: {
      whatDetected: 'Earthmoving vehicle rumble near edge of concession.',
      whereDetected: 'Northern Buffer.',
      whenDetected: '2026-08-28 09:20 UTC.',
      source: 'Alpha-09.',
      aiConfidence: 75,
      supportingSignals: ['Engine signature.'],
      contradictingSignals: [],
      whyFlagged: ['Buffer zone proximity.'],
      whatHumanReviewShouldCheck: ['Concession maintenance log.'],
      disclaimer: 'Acoustic detection.',
    },
    relatedDeviceIds: ['DEV-IOT-042'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00308'],
    timeline: [{ time: '09:20 UTC', action: 'Low frequency alert', actor: 'Alpha-09' }],
  },

  // Cluster C: Kupari Border Checkpoint & Highway BR-319 Corridor (Timber Contraband Hot Zone)
  {
    id: 'ENV-2026-000178',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Counterfeit Timber Transit QR Manifest at Kupari Checkpoint',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Kupari Border Checkpoint Sector (BR-319 km 84)',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1915, lng: -59.8825 },
    timestamp: '2026-09-20 21:15:00 UTC',
    detectionSources: ['Kupari Checkpoint Optical OCR', 'SISFLORA Permit RAG'],
    aiConfidence: 97,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Transit document QR code signed with revoked digital certificate key.',
      whereDetected: 'Kupari Gate Bay 1.',
      whenDetected: '2026-09-20 21:15 UTC.',
      source: 'Automated Document Inspector.',
      aiConfidence: 97,
      supportingSignals: ['Certificate fingerprint revoked on 2026-09-02 by IBAMA.'],
      contradictingSignals: [],
      whyFlagged: ['Fraudulent document presentation.'],
      whatHumanReviewShouldCheck: ['Seize paper documents and hold hauler.'],
      disclaimer: 'Cryptographic validation.',
    },
    relatedDeviceIds: ['DEV-CAM-019'],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00400'],
    timeline: [{ time: '21:15 UTC', action: 'QR signature check failed', actor: 'Kupari Gateway' }],
  },
  {
    id: 'ENV-2026-000174',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Detained Triple-Axle Timber Hauler: Protected Rosewood Discovered',
    severity: 'CRITICAL',
    status: 'INVESTIGATION',
    locationName: 'Kupari Border Checkpoint Sector (Weighbridge Bay 2)',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1895, lng: -59.8798 },
    timestamp: '2026-09-17 04:30:00 UTC',
    detectionSources: ['Checkpoint Weighbridge #2', 'Laser Scanner #1'],
    aiConfidence: 95,
    riskLevel: 'CRITICAL',
    aiExplanation: {
      whatDetected: 'Dalbergia nigra logs concealed beneath outer layer of secondary pine.',
      whereDetected: 'Weighbridge Bay 2.',
      whenDetected: '2026-09-17 04:30 UTC.',
      source: 'Physical inspection triggered by mass density discrepancy.',
      aiConfidence: 95,
      supportingSignals: ['Gross vehicle weight exceeded permit declaration by 38%.'],
      contradictingSignals: [],
      whyFlagged: ['CITES Appendix I protected species trafficking.'],
      whatHumanReviewShouldCheck: ['Forensic wood anatomy sample test.'],
      disclaimer: 'Physical & sensor correlation.',
    },
    relatedDeviceIds: ['DEV-IOT-092'],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00388'],
    timeline: [{ time: '04:30 UTC', action: 'Vehicle impounded for inspection', actor: 'Officer Da Silva' }],
  },
  {
    id: 'ENV-2026-000169',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Volumetric Lidar Scan Discrepancy (+32% volume delta)',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Kupari Border Checkpoint Sector (BR-319)',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1920, lng: -59.8830 },
    timestamp: '2026-09-13 18:40:00 UTC',
    detectionSources: ['Volumetric Lidar Scanner', 'Permit Database'],
    aiConfidence: 92,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Physical scanned volume 31.4 m³ vs declared 23.8 m³ on invoice.',
      whereDetected: 'Kupari Gate.',
      whenDetected: '2026-09-13 18:40 UTC.',
      source: 'Volumetric Lidar.',
      aiConfidence: 92,
      supportingSignals: ['3D mesh reconstruction indicates stacked concealed logs.'],
      contradictingSignals: [],
      whyFlagged: ['Tolerance margin exceeded by 24%.'],
      whatHumanReviewShouldCheck: ['Manual log recount.'],
      disclaimer: 'Lidar volumetric calculation.',
    },
    relatedDeviceIds: ['DEV-IOT-092'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00375'],
    timeline: [{ time: '18:40 UTC', action: 'Lidar volume discrepancy flagged', actor: 'Scanner #1' }],
  },
  {
    id: 'ENV-2026-000165',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Bypass Attempt of Weighbridge via Unpaved Spur Track',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Kupari Border Checkpoint Sector - Bypass Spur',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1870, lng: -59.8770 },
    timestamp: '2026-09-09 02:50:00 UTC',
    detectionSources: ['Thermal Camera CAM-022', 'Road Sensor Loop RS-4'],
    aiConfidence: 90,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Loaded log hauler attempting detour around Kupari checkpoint weighbridge.',
      whereDetected: 'Bypass Spur km 82.',
      whenDetected: '2026-09-09 02:50 UTC.',
      source: 'Thermal camera CAM-022.',
      aiConfidence: 90,
      supportingSignals: ['Vehicle silhouette matches flatbed logging truck.'],
      contradictingSignals: [],
      whyFlagged: ['Intentional weighbridge evasion.'],
      whatHumanReviewShouldCheck: ['Ranger roadblock deployment.'],
      disclaimer: 'Thermal optical detection.',
    },
    relatedDeviceIds: ['DEV-CAM-022'],
    relatedCameraIds: ['DEV-CAM-022'],
    evidenceIds: ['EVD-2026-00364'],
    timeline: [{ time: '02:50 UTC', action: 'Bypass incursion alerted', actor: 'CAM-022' }],
  },
  {
    id: 'ENV-2026-000156',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'False Declaration of Secondary Softwoods at Checkpoint Gate',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Kupari Border Checkpoint Sector (BR-319)',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1905, lng: -59.8810 },
    timestamp: '2026-09-03 08:15:00 UTC',
    detectionSources: ['Bark Texture Optical Classifier', 'Permit Portal'],
    aiConfidence: 85,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Visual bark pattern identified as Jatobá hardwood rather than declared Pine.',
      whereDetected: 'Kupari Checkpoint.',
      whenDetected: '2026-09-03 08:15 UTC.',
      source: 'High-res optical camera at gate.',
      aiConfidence: 85,
      supportingSignals: ['Bark texture convolutional neural net match.'],
      contradictingSignals: [],
      whyFlagged: ['Tax avoidance and illicit hardwood substitution.'],
      whatHumanReviewShouldCheck: ['Officer inspection.'],
      disclaimer: 'Optical AI classification.',
    },
    relatedDeviceIds: ['DEV-CAM-019'],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00338'],
    timeline: [{ time: '08:15 UTC', action: 'Species flag raised', actor: 'Gate Optical AI' }],
  },
  {
    id: 'ENV-2026-000150',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Overweight Gross Tonnage Alert at Scale #1',
    severity: 'INFORMATIONAL',
    status: 'CLOSED',
    locationName: 'Kupari Border Checkpoint Sector',
    zoneId: 'ZN-07',
    coordinates: { lat: -3.1890, lng: -59.8805 },
    timestamp: '2026-08-31 16:30:00 UTC',
    detectionSources: ['Electronic Scale #1'],
    aiConfidence: 94,
    riskLevel: 'LOW',
    aiExplanation: {
      whatDetected: 'Gross vehicle weight 8% above state highway max axle limit.',
      whereDetected: 'Kupari Scale.',
      whenDetected: '2026-08-31 16:30 UTC.',
      source: 'Scale sensor.',
      aiConfidence: 94,
      supportingSignals: ['Weight telemetry.'],
      contradictingSignals: [],
      whyFlagged: ['Highway regulatory compliance.'],
      whatHumanReviewShouldCheck: ['Issue administrative overweight fine.'],
      disclaimer: 'Direct sensor metric.',
    },
    relatedDeviceIds: ['DEV-IOT-092'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00320'],
    timeline: [{ time: '16:30 UTC', action: 'Scale alert', actor: 'Scale #1' }],
  },

  // Cluster D: Rio Negro Tributary & Headwaters (Fire & Thermal Anomaly Hot Zone)
  {
    id: 'ENV-2026-000172',
    type: 'FIRE_SMOKE_ANOMALY',
    title: 'Controlled Burn Crossing Perimeter into Native Peat Forest',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Rio Negro Tributary Headwaters - East Margin',
    zoneId: 'ZN-05',
    coordinates: { lat: -3.1430, lng: -60.1820 },
    timestamp: '2026-09-16 12:40:00 UTC',
    detectionSources: ['VIIRS Active Fire', 'Smoke Sensor DEV-IOT-212'],
    aiConfidence: 91,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Thermal brightness temperature 324K and high particulate matter index.',
      whereDetected: 'Rio Negro Basin East margin.',
      whenDetected: '2026-09-16 12:40 UTC.',
      source: 'VIIRS satellite & IoT smoke sensor.',
      aiConfidence: 91,
      supportingSignals: ['Rapid spread rate under dry wind conditions.'],
      contradictingSignals: [],
      whyFlagged: ['Threatens primary peat forest reserve.'],
      whatHumanReviewShouldCheck: ['Firefighting crew dispatch.'],
      disclaimer: 'Satellite thermal detection.',
    },
    relatedDeviceIds: ['DEV-IOT-212'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00385'],
    timeline: [{ time: '12:40 UTC', action: 'Thermal hotspot alert', actor: 'VIIRS Suomi' }],
  },
  {
    id: 'ENV-2026-000167',
    type: 'FIRE_SMOKE_ANOMALY',
    title: 'Smoldering Ground Fire Smoke Plume Anomaly',
    severity: 'SUSPICIOUS',
    status: 'RESOLVED',
    locationName: 'Rio Negro Tributary Headwaters - North Swale',
    zoneId: 'ZN-05',
    coordinates: { lat: -3.1390, lng: -60.1770 },
    timestamp: '2026-09-10 07:15:00 UTC',
    detectionSources: ['Thermal Drone Flight', 'Air Quality Node AQ-04'],
    aiConfidence: 86,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Sub-surface smoldering thermal trace with continuous CO emissions.',
      whereDetected: 'North Swale peat layer.',
      whenDetected: '2026-09-10 07:15 UTC.',
      source: 'Air quality node AQ-04.',
      aiConfidence: 86,
      supportingSignals: ['Carbon monoxide spike to 28 ppm.'],
      contradictingSignals: [],
      whyFlagged: ['Peat soil combustion risk.'],
      whatHumanReviewShouldCheck: ['Ground water trenching.'],
      disclaimer: 'Sensor gas reading.',
    },
    relatedDeviceIds: ['DEV-IOT-212'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00368'],
    timeline: [{ time: '07:15 UTC', action: 'Air quality alert', actor: 'AQ-04' }],
  },
  {
    id: 'ENV-2026-000161',
    type: 'FIRE_SMOKE_ANOMALY',
    title: 'Thermal Anomaly Detected in Riparian Buffer',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Rio Negro Tributary Headwaters',
    zoneId: 'ZN-05',
    coordinates: { lat: -3.1440, lng: -60.1850 },
    timestamp: '2026-09-06 14:50:00 UTC',
    detectionSources: ['MODIS Thermal Hotspot', 'Optical Sentinel-2'],
    aiConfidence: 82,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Thermal signature of 308K.',
      whereDetected: 'Riparian buffer zone.',
      whenDetected: '2026-09-06 14:50 UTC.',
      source: 'MODIS pass.',
      aiConfidence: 82,
      supportingSignals: ['Moderate fire radiative power.'],
      contradictingSignals: [],
      whyFlagged: ['Proximity to reserve boundary.'],
      whatHumanReviewShouldCheck: ['Observe subsequent satellite pass.'],
      disclaimer: 'MODIS algorithm.',
    },
    relatedDeviceIds: ['DEV-IOT-212'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00352'],
    timeline: [{ time: '14:50 UTC', action: 'Hotspot logged', actor: 'MODIS' }],
  },
  {
    id: 'ENV-2026-000147',
    type: 'FIRE_SMOKE_ANOMALY',
    title: 'Agricultural Land-Clearing Burn Flared near Basin Boundary',
    severity: 'INFORMATIONAL',
    status: 'CLOSED',
    locationName: 'Rio Negro Tributary Headwaters - South Fringe',
    zoneId: 'ZN-05',
    coordinates: { lat: -3.1460, lng: -60.1790 },
    timestamp: '2026-08-29 18:10:00 UTC',
    detectionSources: ['VIIRS Thermal'],
    aiConfidence: 80,
    riskLevel: 'LOW',
    aiExplanation: {
      whatDetected: 'Low intensity thermal flare.',
      whereDetected: 'South Fringe agricultural plot.',
      whenDetected: '2026-08-29 18:10 UTC.',
      source: 'VIIRS.',
      aiConfidence: 80,
      supportingSignals: ['Small thermal footprint.'],
      contradictingSignals: [],
      whyFlagged: ['Season burn monitoring.'],
      whatHumanReviewShouldCheck: ['Verify seasonal burn authorization.'],
      disclaimer: 'Thermal algorithm.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00310'],
    timeline: [{ time: '18:10 UTC', action: 'Detection archived', actor: 'VIIRS' }],
  },

  // Cluster E: Emerald River Corridor (Waterborne Machinery & Timber Raft Hot Zone)
  {
    id: 'ENV-2026-000177',
    type: 'UNAUTHORIZED_ENTRY_RESTRICTED_ZONE',
    title: 'Unregistered Diesel Push-Tug Navigating Upstream at Night',
    severity: 'HIGH_PRIORITY',
    status: 'VERIFIED',
    locationName: 'Emerald River Corridor - River Mile 38',
    zoneId: 'ZN-02',
    coordinates: { lat: -3.1668, lng: -59.9840 },
    timestamp: '2026-09-20 03:40:00 UTC',
    detectionSources: ['River Camera CAM-019', 'Acoustic Hydrophone HYD-04'],
    aiConfidence: 93,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Vessel running with extinguished navigation lights carrying heavy equipment.',
      whereDetected: 'Emerald River Mile 38.',
      whenDetected: '2026-09-20 03:40 UTC.',
      source: 'Camera CAM-019 low-light.',
      aiConfidence: 93,
      supportingSignals: ['Hydrophone cavitation profile matches commercial tug.'],
      contradictingSignals: [],
      whyFlagged: ['Restricted river waterway after sunset.'],
      whatHumanReviewShouldCheck: ['Dispatch river patrol boat.'],
      disclaimer: 'Hydro-optical sensor correlation.',
    },
    relatedDeviceIds: ['DEV-CAM-019'],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00398'],
    timeline: [{ time: '03:40 UTC', action: 'River sensor triggered', actor: 'HYD-04' }],
  },
  {
    id: 'ENV-2026-000173',
    type: 'SUSPICIOUS_TIMBER_TRANSPORT',
    title: 'Moored Floating Timber Raft Assembled in Buffer Zone',
    severity: 'HIGH_PRIORITY',
    status: 'INVESTIGATION',
    locationName: 'Emerald River Corridor - Island Bend',
    zoneId: 'ZN-02',
    coordinates: { lat: -3.1635, lng: -59.9790 },
    timestamp: '2026-09-16 16:20:00 UTC',
    detectionSources: ['Drone Patrol Recon Delta', 'Optical AI'],
    aiConfidence: 89,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Timber raft containing approx. 95 freshly cut hardwood logs tied to riverbank.',
      whereDetected: 'Emerald River Island Bend.',
      whenDetected: '2026-09-16 16:20 UTC.',
      source: 'Drone Recon flight.',
      aiConfidence: 89,
      supportingSignals: ['Fresh debarked log surface reflectances.'],
      contradictingSignals: [],
      whyFlagged: ['Clandestine riverine timber transport staging.'],
      whatHumanReviewShouldCheck: ['Secure logs and identify towing boat.'],
      disclaimer: 'Aerial visual inspection.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00386'],
    timeline: [{ time: '16:20 UTC', action: 'Timber raft discovered', actor: 'Drone Delta' }],
  },
  {
    id: 'ENV-2026-000163',
    type: 'UNAUTHORIZED_ENTRY_RESTRICTED_ZONE',
    title: 'Motorized Wooden Skiff Operating near Riparian Spawning Habitat',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Emerald River Corridor - River Mile 44',
    zoneId: 'ZN-02',
    coordinates: { lat: -3.1675, lng: -59.9860 },
    timestamp: '2026-09-08 22:10:00 UTC',
    detectionSources: ['Acoustic Hydrophone HYD-04'],
    aiConfidence: 82,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'High-RPM 2-stroke outboard engine acoustic signature.',
      whereDetected: 'Emerald River Mile 44.',
      whenDetected: '2026-09-08 22:10 UTC.',
      source: 'Hydrophone HYD-04.',
      aiConfidence: 82,
      supportingSignals: ['Outboard engine acoustic curve.'],
      contradictingSignals: [],
      whyFlagged: ['Protected fish spawning season river curfew.'],
      whatHumanReviewShouldCheck: ['Routine river patrol.'],
      disclaimer: 'Acoustic classification.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00358'],
    timeline: [{ time: '22:10 UTC', action: 'Outboard engine detected', actor: 'HYD-04' }],
  },
  {
    id: 'ENV-2026-000154',
    type: 'HEAVY_MACHINERY_ENCROACHMENT',
    title: 'Excavator Disembarking from River Barge at Unofficial Landing',
    severity: 'CRITICAL',
    status: 'INVESTIGATION',
    locationName: 'Emerald River Corridor - North Bank Landing',
    zoneId: 'ZN-02',
    coordinates: { lat: -3.1620, lng: -59.9760 },
    timestamp: '2026-09-02 04:15:00 UTC',
    detectionSources: ['Camera CAM-019', 'Acoustic Node DEV-IOT-108'],
    aiConfidence: 96,
    riskLevel: 'CRITICAL',
    aiExplanation: {
      whatDetected: 'Cat 320 excavator unloaded onto natural riverbank in core protected reserve.',
      whereDetected: 'Emerald River North Bank Landing.',
      whenDetected: '2026-09-02 04:15 UTC.',
      source: 'Camera CAM-019 night vision.',
      aiConfidence: 96,
      supportingSignals: ['Clear optical classification and metal ramp deployment sound.'],
      contradictingSignals: [],
      whyFlagged: ['Equipment intended for illegal forest interior penetration.'],
      whatHumanReviewShouldCheck: ['Priority interdiction.'],
      disclaimer: 'Optical night vision detection.',
    },
    relatedDeviceIds: ['DEV-CAM-019', 'DEV-IOT-108'],
    relatedCameraIds: ['DEV-CAM-019'],
    evidenceIds: ['EVD-2026-00332'],
    timeline: [{ time: '04:15 UTC', action: 'Unloading classified', actor: 'CAM-019 AI' }],
  },
  {
    id: 'ENV-2026-000148',
    type: 'WILDLIFE_HABITAT_THREAT',
    title: 'Poaching Trap and Foot Incursion near River Sandbank',
    severity: 'INFORMATIONAL',
    status: 'CLOSED',
    locationName: 'Emerald River Corridor - Sandbank 12',
    zoneId: 'ZN-02',
    coordinates: { lat: -3.1690, lng: -59.9880 },
    timestamp: '2026-08-28 17:30:00 UTC',
    detectionSources: ['Field Patrol Team Alpha'],
    aiConfidence: 88,
    riskLevel: 'LOW',
    aiExplanation: {
      whatDetected: 'Wire snare line removed during routine foot patrol.',
      whereDetected: 'Sandbank 12.',
      whenDetected: '2026-08-28 17:30 UTC.',
      source: 'Field Patrol inspection.',
      aiConfidence: 88,
      supportingSignals: ['Snare collected and logged.'],
      contradictingSignals: [],
      whyFlagged: ['Threat to giant river otter and tapir watering routes.'],
      whatHumanReviewShouldCheck: ['Sweep adjacent bank.'],
      disclaimer: 'Field officer verification.',
    },
    relatedDeviceIds: [],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00312'],
    timeline: [{ time: '17:30 UTC', action: 'Snare neutralized', actor: 'Patrol Alpha' }],
  },

  // Cluster F: Highlands Bamboo & Cloud Forest (Wildlife Poaching & Canopy Disturbance)
  {
    id: 'ENV-2026-000181',
    type: 'WILDLIFE_HABITAT_THREAT',
    title: 'Acoustic Gunshot / Explosion Harmonic Flag in Cloud Forest',
    severity: 'HIGH_PRIORITY',
    status: 'UNDER_REVIEW',
    locationName: 'Highlands Bamboo & Cloud Forest - Ridge Crest',
    zoneId: 'ZN-08',
    coordinates: { lat: -3.0520, lng: -60.0620 },
    timestamp: '2026-09-23 05:40:00 UTC',
    detectionSources: ['Acoustic Sensor DEV-IOT-188'],
    aiConfidence: 87,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Impulse acoustic shockwave (92 dB) consistent with high-caliber firearm discharge.',
      whereDetected: 'Highlands Ridge Crest.',
      whenDetected: '2026-09-23 05:40 UTC.',
      source: 'Canopy Soundscape Node 88.',
      aiConfidence: 87,
      supportingSignals: ['Sharp acoustic rise time < 5ms and echo reverberation.'],
      contradictingSignals: [],
      whyFlagged: ['Threat to endangered Jaguar and Harpy Eagle nesting sanctuary.'],
      whatHumanReviewShouldCheck: ['Acoustic triangulated coordinates review.'],
      disclaimer: 'Acoustic impulse analysis.',
    },
    relatedDeviceIds: ['DEV-IOT-188'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00408'],
    timeline: [{ time: '05:40 UTC', action: 'Impulse wave classified', actor: 'Node 88' }],
  },
  {
    id: 'ENV-2026-000170B',
    type: 'UNAUTHORIZED_ENTRY_RESTRICTED_ZONE',
    title: 'Camera Motion Capture: Armed Hunting Party in Cloud Forest',
    severity: 'HIGH_PRIORITY',
    status: 'INVESTIGATION',
    locationName: 'Highlands Bamboo & Cloud Forest - Sector 3',
    zoneId: 'ZN-08',
    coordinates: { lat: -3.0485, lng: -60.0590 },
    timestamp: '2026-09-14 22:30:00 UTC',
    detectionSources: ['Trail Camera CAM-072'],
    aiConfidence: 91,
    riskLevel: 'HIGH',
    aiExplanation: {
      whatDetected: 'Three individuals equipped with firearms traversing off-trail ridge.',
      whereDetected: 'Cloud Forest Sector 3.',
      whenDetected: '2026-09-14 22:30 UTC.',
      source: 'Trail Camera CAM-072 motion trigger.',
      aiConfidence: 91,
      supportingSignals: ['Weapon optical bounding box with 91% confidence.'],
      contradictingSignals: [],
      whyFlagged: ['Armed poaching party in strictly protected wildlife sanctuary.'],
      whatHumanReviewShouldCheck: ['Dispatch armed tactical ranger team.'],
      disclaimer: 'Optical AI classification.',
    },
    relatedDeviceIds: ['DEV-CAM-072'],
    relatedCameraIds: ['DEV-CAM-072'],
    evidenceIds: ['EVD-2026-00380'],
    timeline: [{ time: '22:30 UTC', action: 'Motion trigger photo captured', actor: 'CAM-072' }],
  },
  {
    id: 'ENV-2026-000157',
    type: 'WILDLIFE_HABITAT_THREAT',
    title: 'Acoustic Gunshot Anomaly: Highlands Jaguar Habitat',
    severity: 'SUSPICIOUS',
    status: 'CLOSED',
    locationName: 'Highlands Bamboo & Cloud Forest',
    zoneId: 'ZN-08',
    coordinates: { lat: -3.0540, lng: -60.0650 },
    timestamp: '2026-09-03 23:10:00 UTC',
    detectionSources: ['Canopy Soundscape Node 88'],
    aiConfidence: 81,
    riskLevel: 'MEDIUM',
    aiExplanation: {
      whatDetected: 'Possible firearm impulse wave in deep cloud forest.',
      whereDetected: 'Highlands Bamboo Zone.',
      whenDetected: '2026-09-03 23:10 UTC.',
      source: 'Node 88.',
      aiConfidence: 81,
      supportingSignals: ['Acoustic impulse signature.'],
      contradictingSignals: ['Thunder reverberation reported in sector.'],
      whyFlagged: ['High risk wildlife habitat.'],
      whatHumanReviewShouldCheck: ['Ranger check.'],
      disclaimer: 'Acoustic waveform analysis.',
    },
    relatedDeviceIds: ['DEV-IOT-188'],
    relatedCameraIds: [],
    evidenceIds: ['EVD-2026-00340'],
    timeline: [{ time: '23:10 UTC', action: 'Impulse waveform logged', actor: 'Node 88' }],
  },
];

// 15 Investigation Cases
export const MOCK_CASES: InvestigationCase[] = [
  {
    id: 'CASE-2026-0089',
    title: 'Operation Emerald Shield: Organized Timber Syndicate in Northern Canopy',
    leadInvestigator: 'Inspector Marcus Reed',
    investigatorBadge: 'FG-INV-44',
    status: 'ACTIVE_INVESTIGATION',
    priority: 'CRITICAL',
    openedDate: '2026-09-12',
    targetZone: 'Northern Canopy Wildlife Corridor',
    primaryViolation: 'Violations of Forestry Act 2022 Sec. 42 (Unlawful Clearing) & Penal Code Sec. 288 (Commercial Timber Trafficking)',
    incidentIds: ['ENV-2026-000182', 'ENV-2026-000184'],
    evidenceIds: ['EVD-2026-00412', 'EVD-2026-00413', 'EVD-2026-00418', 'EVD-2026-00419'],
    suspectVehicles: ['TRK-9021-BR', 'AMZ-8894 (Suspect Flatbed)', 'Heavy Loader Cat-966'],
    suspectEntities: ['Madeiras da Amazônia Trans-Logística Ltda', 'Unidentified Logging Crew Delta'],
    checklist: [
      { task: 'Capture and cryptographically seal high-res drone footage of road penetration', completed: true, completedAt: '2026-09-23 21:00 UTC', completedBy: 'Pilot Sato' },
      { task: 'Correlate weighbridge weight discrepancy logs with mill delivery addresses', completed: true, completedAt: '2026-09-24 07:30 UTC', completedBy: 'Inv. Clara Gomes' },
      { task: 'Execute forensic GPS extraction on seized timber hauler', completed: false },
      { task: 'Cross-reference satellite multispectral canopy loss with licensed concession boundaries', completed: true, completedAt: '2026-09-24 04:00 UTC', completedBy: 'Analyst Chen' },
      { task: 'Draft formal prosecutorial dossier for Environmental Public Ministry', completed: false },
    ],
    formalDossierSummary: 'Comprehensive evidence dossier compiling acoustic recordings, multi-angle CCTV vehicle captures, satellite time-series canopy disruption, and fraudulent timber volume transport documentation for judicial referral.',
    chainOfCustodyVerified: true,
  },
  {
    id: 'CASE-2026-0084',
    title: 'Kupari Border Checkpoint Transit Fraud Investigation',
    leadInvestigator: 'Inspector Clara Gomes',
    investigatorBadge: 'FG-INV-12',
    status: 'EVIDENCE_COLLECTION',
    priority: 'HIGH',
    openedDate: '2026-09-18',
    targetZone: 'Kupari Border Checkpoint Sector',
    primaryViolation: 'Timber Transit Regulation 2024 Rule 14 & Electronic Manifest Fraud',
    incidentIds: ['ENV-2026-000183'],
    evidenceIds: ['EVD-2026-00416', 'EVD-2026-00417'],
    suspectVehicles: ['TRK-9021-BR', 'VOL-4402-RO'],
    suspectEntities: ['Transportes Florestais do Norte'],
    checklist: [
      { task: 'Physical measurement and species classification of detained logs', completed: true, completedAt: '2026-09-24 08:00 UTC', completedBy: 'Forest Officer Da Silva' },
      { task: 'Audit origin sawmill SISFLORA electronic issuing account', completed: false },
    ],
    formalDossierSummary: 'Investigation into systemic under-declaration of high-value Rosewood disguised as secondary softwoods at border transit gates.',
    chainOfCustodyVerified: true,
  },
];

// 50 Timber Transport Records
export const MOCK_TIMBER_RECORDS: TimberTransportRecord[] = [
  {
    id: 'TMB-2026-9041',
    permitId: 'PMT-2026-4412',
    transportAuthorization: 'AUTH-IBAMA-2026-09918',
    vehicleRegistration: 'TRK-9021-BR',
    driverName: 'Carlos M. Ferreira',
    originConcession: 'Blackwood Sustainable Forestry Concession (Plot 14)',
    destinationFacility: 'Porto Velho Commercial Sawmill Facility #4',
    declaredSpecies: 'Pinus caribaea / Eucalyptus',
    declaredQuantityM3: 18.0,
    recordedQuantityM3: 27.4,
    discrepancyM3: 9.4,
    timestamp: '2026-09-24 06:45:00 UTC',
    checkpointName: 'Kupari Border Checkpoint (BR-319)',
    coordinates: { lat: -3.1902, lng: -59.8812 },
    status: 'DISCREPANCY_DETECTED',
    inspectionNotes: 'Gross scale weight discrepancy +48.9%. High density wood observed. Vehicle held in Inspection Bay 2.',
    checkedByOfficer: 'Forest Officer Da Silva (Badge FO-309)',
  },
  {
    id: 'TMB-2026-9042',
    permitId: 'PMT-2026-3891',
    transportAuthorization: 'AUTH-IBAMA-2026-08412',
    vehicleRegistration: 'AMZ-4412-RO',
    driverName: 'Joao Paulo Rodrigues',
    originConcession: 'Blackwood Sustainable Forestry Concession (Plot 08)',
    destinationFacility: 'Manaus Certified Timber Export Terminal',
    declaredSpecies: 'Hymenaea courbaril (Jatobá)',
    declaredQuantityM3: 24.0,
    recordedQuantityM3: 24.2,
    discrepancyM3: 0.2,
    timestamp: '2026-09-24 05:20:00 UTC',
    checkpointName: 'Kupari Border Checkpoint (BR-319)',
    coordinates: { lat: -3.1902, lng: -59.8812 },
    status: 'AUTHORIZED',
    inspectionNotes: 'Physical logs match electronic barcode tags. Volume within 1% allowable error margin. Approved for transit.',
    checkedByOfficer: 'Forest Officer Da Silva (Badge FO-309)',
  },
  {
    id: 'TMB-2026-9043',
    permitId: 'PMT-2026-1109',
    transportAuthorization: 'AUTH-IBAMA-2026-07714',
    vehicleRegistration: 'PA-8891-MT',
    driverName: 'Marcos Aurelio Souza',
    originConcession: 'Rio Madeira Managed Farm Unit',
    destinationFacility: 'Santarém Plywood Processing Plant',
    declaredSpecies: 'Cedrela odorata (Cedar)',
    declaredQuantityM3: 30.0,
    recordedQuantityM3: 38.5,
    discrepancyM3: 8.5,
    timestamp: '2026-09-23 22:15:00 UTC',
    checkpointName: 'Emerald River Ferry Crossing',
    coordinates: { lat: -3.1650, lng: -59.9800 },
    status: 'HELD_FOR_INSPECTION',
    inspectionNotes: 'Excess load over gross vehicle rating; permit QR code failed cryptographic signature verification.',
    checkedByOfficer: 'Inspector Clara Gomes',
  },
];

// Digital Evidence Repository with SHA-256 Hashes and Chain of Custody
export const MOCK_EVIDENCE: EvidenceItem[] = [
  {
    id: 'EVD-2026-00412',
    incidentId: 'ENV-2026-000182',
    title: 'CCTV Night Vision Capture: Flatbed Truck & Forestry Loader Incursion',
    type: 'VIDEO',
    sourceDevice: 'DEV-CAM-041 (Thermal & Low-Light Camera)',
    timestamp: '2026-09-24 02:18:15 UTC',
    locationName: 'Tapir Ridge Strict Nature Reserve - Access Trail Delta',
    coordinates: { lat: -3.1254, lng: -60.0248 },
    uploadedBy: 'Automated Edge Ingestion Gateway Node-04',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    sizeBytes: 48512900,
    fileUrl: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=1200&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=400&auto=format&fit=crop&q=80',
    isVerifiedIntegrity: true,
    metadata: {
      durationSeconds: 45,
      codec: 'H.265 / HEVC',
      fps: 30,
      bitrateKbps: 8400,
      tamperResistantWatermark: 'FG-SIGN-2026-88091-VALID',
    },
    chainOfCustody: [
      {
        id: 'COC-01',
        timestamp: '2026-09-24 02:18:30 UTC',
        action: 'CAPTURED',
        actorName: 'DEV-CAM-041 Hardware Module',
        actorRole: 'EDGE_DEVICE',
        actorAgency: 'FORESTGUARD IoT Core',
        previousState: 'LOCAL_SENSOR_BUFFER',
        newState: 'STORED_ENCRYPTED_NVRAM',
        notes: 'Captured via hardware motion trigger and onboard optical classifier.',
      },
      {
        id: 'COC-02',
        timestamp: '2026-09-24 02:19:02 UTC',
        action: 'UPLOADED',
        actorName: 'Secure Starlink Ingestion Service',
        actorRole: 'SYSTEM_DAEMON',
        actorAgency: 'FORESTGUARD Backend Cloud',
        previousState: 'STORED_ENCRYPTED_NVRAM',
        newState: 'EVIDENCE_VAULT_INGESTED',
        notes: 'Transmitted over TLS 1.3 encrypted mesh channel.',
      },
      {
        id: 'COC-03',
        timestamp: '2026-09-24 02:19:05 UTC',
        action: 'HASH_GENERATED',
        actorName: 'Cryptographic Integrity Engine',
        actorRole: 'SYSTEM_SECURITY',
        actorAgency: 'FORESTGUARD Security Module',
        previousState: 'EVIDENCE_VAULT_INGESTED',
        newState: 'HASH_SEALED',
        notes: 'SHA-256 seal computed and recorded in tamper-evident ledger.',
      },
      {
        id: 'COC-04',
        timestamp: '2026-09-24 02:35:44 UTC',
        action: 'REVIEWED',
        actorName: 'Elena Vance',
        actorRole: 'SUPER_ADMIN',
        actorAgency: 'Dept. of Forest Conservation',
        previousState: 'HASH_SEALED',
        newState: 'REVIEWED_PENDING_TRIAGE',
        notes: 'Examined vehicle dimensions, license plate angle, and tree species in payload.',
      },
    ],
  },
  {
    id: 'EVD-2026-00413',
    incidentId: 'ENV-2026-000182',
    title: 'Acoustic Sensor Audio Spectrogram & Raw WAV: 2.85 kHz Chainsaw Signature',
    type: 'AUDIO',
    sourceDevice: 'DEV-IOT-014 (Acoustic Triangulator A-204)',
    timestamp: '2026-09-24 02:14:08 UTC',
    locationName: 'Tapir Ridge Strict Nature Reserve - Radial Bearing 142°',
    coordinates: { lat: -3.1280, lng: -60.0310 },
    uploadedBy: 'Automated Acoustic Ingestion Node',
    sha256Hash: '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945',
    sizeBytes: 8920400,
    fileUrl: 'https://cdn.freesound.org/previews/512/512128_649468-lq.mp3',
    isVerifiedIntegrity: true,
    metadata: {
      sampleRateHz: 48000,
      channels: 1,
      format: 'FLAC / 24-bit PCM',
      peakDecibels: 78.4,
    },
    chainOfCustody: [
      {
        id: 'COC-05',
        timestamp: '2026-09-24 02:14:20 UTC',
        action: 'CAPTURED',
        actorName: 'Acoustic Node A-204',
        actorRole: 'EDGE_DEVICE',
        actorAgency: 'FORESTGUARD IoT Core',
        previousState: 'RAW_MEMS_STREAM',
        newState: 'ENCRYPTED_FILE',
      },
      {
        id: 'COC-06',
        timestamp: '2026-09-24 02:14:45 UTC',
        action: 'HASH_GENERATED',
        actorName: 'Cryptographic Integrity Engine',
        actorRole: 'SYSTEM_SECURITY',
        actorAgency: 'FORESTGUARD Security Module',
        previousState: 'ENCRYPTED_FILE',
        newState: 'HASH_SEALED',
      },
    ],
  },
  {
    id: 'EVD-2026-00414',
    incidentId: 'ENV-2026-000182',
    title: 'Sentinel-2 Level-2A MSI Surface Reflectance Canopy Loss Tile',
    type: 'SATELLITE_IMAGE',
    sourceDevice: 'ESA Sentinel-2 Multispectral Constellation',
    timestamp: '2026-09-23 14:42:00 UTC',
    locationName: 'Tapir Ridge Strict Nature Reserve (Tile T20MMA)',
    coordinates: { lat: -3.1254, lng: -60.0248 },
    uploadedBy: 'Copernicus Hub Automated Harvester',
    sha256Hash: '9a6d4c382109ba249fecba11283d7ac4809228a7e029f60e945c26b801a2f643',
    sizeBytes: 124800000,
    fileUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&auto=format&fit=crop&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=400&auto=format&fit=crop&q=80',
    isVerifiedIntegrity: true,
    metadata: {
      cloudCoverPercent: 2.1,
      ndviBaseline: 0.82,
      ndviDetected: 0.54,
      hectaresLost: 4.8,
    },
    chainOfCustody: [
      {
        id: 'COC-07',
        timestamp: '2026-09-23 16:00:00 UTC',
        action: 'UPLOADED',
        actorName: 'Copernicus Harvester Service',
        actorRole: 'DATA_PIPELINE',
        actorAgency: 'FORESTGUARD Satellite Ingestion',
        previousState: 'ESA_API',
        newState: 'GEO_TIFF_VAULT',
      },
    ],
  },
  {
    id: 'EVD-2026-00416',
    incidentId: 'ENV-2026-000183',
    title: 'Checkpoint Kupari Automated Laser Volumetric Log Scan & Weight Slip',
    type: 'DOCUMENT',
    sourceDevice: 'Weighbridge Scanner #2 System',
    timestamp: '2026-09-24 06:46:12 UTC',
    locationName: 'Kupari Border Transit Checkpoint',
    coordinates: { lat: -3.1902, lng: -59.8812 },
    uploadedBy: 'Forest Officer Da Silva',
    sha256Hash: '32b879ec3d82a17056094b8e265c7f846e276f5b9d311894b910e98031dcf504',
    sizeBytes: 3410200,
    fileUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&auto=format&fit=crop&q=80',
    isVerifiedIntegrity: true,
    metadata: {
      grossWeightKg: 44200,
      tareWeightKg: 14500,
      netTimberWeightKg: 29700,
      calculatedVolumeM3: 27.4,
    },
    chainOfCustody: [
      {
        id: 'COC-08',
        timestamp: '2026-09-24 06:48:00 UTC',
        action: 'UPLOADED',
        actorName: 'Forest Officer Da Silva',
        actorRole: 'FOREST_OFFICER',
        actorAgency: 'Forest Dept. Transit Enforcement',
        previousState: 'WEIGHBRIDGE_TERMINAL',
        newState: 'EVIDENCE_REPOSITORY',
      },
    ],
  },
];

// Legal Knowledge Base for Legal RAG with real statutory citations
export const MOCK_LEGAL_DOCUMENTS: LegalDocument[] = [
  {
    id: 'LEG-DOC-01',
    title: 'National Forest & Biodiversity Protection Act of 2022',
    shortCode: 'NFBPA-2022',
    jurisdiction: 'Federal Environmental Protection Authority',
    category: 'FOREST_LAW',
    documentDate: '2022-04-15',
    version: 'Revised Edition 2.1 (2024)',
    officialSource: 'Official Federal Gazette No. 84, Vol. 14, pp. 1120-1188',
    sections: [
      {
        sectionNumber: 'Section 42',
        title: 'Prohibition of Mechanical Logging in Core Conservation Zones',
        page: 28,
        text: 'No person, corporation, or entity shall operate, introduce, or maintain chainsaws, tractors, skidders, or heavy mechanical clearing equipment within designated Core Protected Nature Reserves without an express scientific permit issued under Section 19. Any unauthorized entry with logging apparatus constitutes a Category A statutory environmental crime.',
        penalties: 'Mandatory vehicle and equipment forfeiture, custodial sentence of 3 to 8 years, and statutory remediation fine of $50,000 per hectare cleared.',
      },
      {
        sectionNumber: 'Section 47',
        title: 'Nighttime Extraction and Transit Prohibition',
        page: 32,
        text: 'All commercial felling, yarding, hauling, or loading of round logs between 18:00 hours and 06:00 hours local time is strictly prohibited regardless of whether the concession holds an active management plan, except where specific continuous-operation permits are registered with the regional directorate.',
        penalties: 'Immediate suspension of commercial concession license for 180 days and administrative fine of $25,000.',
      },
      {
        sectionNumber: 'Section 65',
        title: 'Obligations of Chain of Custody & Document Integrity',
        page: 45,
        text: 'All roundwood timber transported on public roads, waterways, or rail corridors must carry physical barcode tags matching the electronic transit manifest (SISFLORA / DOF). A discrepancy exceeding 5% in volume or any substitution of high-value protected species invalidates the transit authorization ab initio.',
        penalties: 'Seizure of total cargo, impoundment of carrier vehicle, and criminal prosecution under Commercial Fraud statutes.',
      },
    ],
  },
  {
    id: 'LEG-DOC-02',
    title: 'Timber Transit and Electronic Manifest Regulation (Regulation 2024/14)',
    shortCode: 'TTR-2024',
    jurisdiction: 'Department of Forestry & Trade Standards',
    category: 'TIMBER_TRANSIT',
    documentDate: '2024-01-10',
    version: 'Official Guideline 2024.1',
    officialSource: 'Forestry Commission Regulatory Circular 2024-03',
    sections: [
      {
        sectionNumber: 'Article 8',
        title: 'Checkpoint Weighbridge Verification and Species Density Standards',
        page: 12,
        text: 'Officers at authorized transit checkpoints possess statutory power to hold any carrier vehicle where volumetric laser scan or weighbridge readings deviate by more than 5% from declared permit tonnage. If wood density indicates hardwood substitution (density >= 0.85 g/cm³ when softwoods are declared), the officer must order mandatory offloading and physical inspection.',
        penalties: 'Immediate 72-hour administrative detention of carrier and driver pending forensic wood sample analysis.',
      },
      {
        sectionNumber: 'Article 14',
        title: 'Buffer Zone Transit Authorizations',
        page: 18,
        text: 'Transportation of forest products across buffer corridors requires an active Digital Transport Document (DDF) detailing origin coordinates, approved route geometry, GPS tracking transponder ID, and designated checkpoint gates. Deviation from approved route geometry by more than 500 meters without written distress notification revokes the permit immediately.',
        penalties: 'Administrative fine of $15,000 and carrier registration suspension.',
      },
    ],
  },
  {
    id: 'LEG-DOC-03',
    title: 'Protected Wildlife & Flora Conservation Code (Title 18)',
    shortCode: 'PWFC-T18',
    jurisdiction: 'National Environmental Enforcement Council',
    category: 'PROTECTED_AREA_CODE',
    documentDate: '2021-08-30',
    version: 'Consolidated Statute 2025',
    officialSource: 'National Code of Environmental Statutes, Title 18, Subchapter C',
    sections: [
      {
        sectionNumber: 'Section 104',
        title: 'Strict Nature Reserves: Zero-Extraction Mandate',
        page: 7,
        text: 'In Class 1 Strict Nature Reserves, human presence is restricted exclusively to authorized scientific observation and sovereign environmental protection patrols. No harvesting, soil disturbance, or road building of any description is permitted. The defense of lack of boundary demarcation shall not be recognized where digital GPS boundary coordinates are gazetted.',
        penalties: 'Custodial imprisonment up to 10 years for organized environmental destruction.',
      },
      {
        sectionNumber: 'Section 112',
        title: 'Protection of CITES Appendix I & II Timber Species',
        page: 15,
        text: 'Special protections apply to Dalbergia nigra (Brazilian Rosewood), Handroanthus spp. (Ipê), and Swietenia macrophylla (Big-Leaf Mahogany). Any harvest or commercial transit requires individual stem registration, micro-tagging, and international CITES export certificates.',
        penalties: 'Confiscation of timber, permanent revocation of forestry concession rights, and criminal referral.',
      },
    ],
  },
];

// 5 Field Patrol Teams
export const MOCK_FIELD_TEAMS: FieldPatrolTeam[] = [
  {
    id: 'TEAM-ALPHA',
    name: 'Ranger Rapid Interdiction Alpha',
    callsign: 'Alpha-Leader',
    rangerCount: 6,
    leaderName: 'Capt. Mateo Santos',
    coordinates: { lat: -3.1290, lng: -60.0350 },
    batteryPercent: 88,
    status: 'INVESTIGATING_INCIDENT',
    assignedIncidentId: 'ENV-2026-000182',
    lastPingTime: '2m ago',
  },
  {
    id: 'TEAM-BRAVO',
    name: 'Ranger Mobile Patrol Bravo',
    callsign: 'Bravo-Two',
    rangerCount: 4,
    leaderName: 'Sgt. Leila Torres',
    coordinates: { lat: -3.0900, lng: -60.1100 },
    batteryPercent: 94,
    status: 'ON_PATROL',
    assignedIncidentId: 'ENV-2026-000184',
    lastPingTime: '4m ago',
  },
  {
    id: 'TEAM-CHARLIE',
    name: 'River Patrol Unit Charlie',
    callsign: 'Charlie-River',
    rangerCount: 5,
    leaderName: 'Lt. Gabriel Costa',
    coordinates: { lat: -3.1620, lng: -59.9850 },
    batteryPercent: 78,
    status: 'INVESTIGATING_INCIDENT',
    assignedIncidentId: 'ENV-2026-000186',
    lastPingTime: '1m ago',
  },
  {
    id: 'TEAM-DELTA',
    name: 'Canopy Drone Recon Team Delta',
    callsign: 'Delta-Sky',
    rangerCount: 3,
    leaderName: 'Pilot Officer Kenji Sato',
    coordinates: { lat: -3.0800, lng: -60.1200 },
    batteryPercent: 62,
    status: 'ON_PATROL',
    lastPingTime: 'Just now',
  },
  {
    id: 'TEAM-ECHO',
    name: 'Station Perimeter Guard Echo',
    callsign: 'Echo-Base',
    rangerCount: 4,
    leaderName: 'Sgt. Maria Rossi',
    coordinates: { lat: -3.2450, lng: -59.9200 },
    batteryPercent: 98,
    status: 'RETURNING_TO_BASE',
    lastPingTime: '8m ago',
  },
];

// Audit Log Entries
export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-2026-00941',
    timestamp: '2026-09-24 10:22:15 UTC',
    userId: 'usr-admin-01',
    userName: 'Cmdr. Elena Vance',
    userRole: 'SUPER_ADMIN',
    action: 'INCIDENT_REVIEW_STATUS_CHANGED',
    targetEntity: 'Incident',
    targetId: 'ENV-2026-000182',
    ipAddress: '10.14.88.2 (Encrypted VPN)',
    details: 'Status transitioned from DETECTED to UNDER_REVIEW. Dispatched alert to Field Team Alpha.',
    tamperSealHash: 'a7c93812fa48e91024cd9a3b81726a8f1029348bca612e093847261a8ef1092b',
  },
  {
    id: 'AUD-2026-00940',
    timestamp: '2026-09-24 07:15:20 UTC',
    userId: 'usr-fo-309',
    userName: 'Forest Officer Da Silva',
    userRole: 'FOREST_OFFICER',
    action: 'VEHICLE_HOLD_ORDER_ISSUED',
    targetEntity: 'Vehicle',
    targetId: 'TRK-9021-BR',
    ipAddress: '10.14.88.42 (Kupari Weighbridge Terminal)',
    details: 'Ordered mandatory vehicle hold for TRK-9021-BR under Regulation 2024/14 Art. 8 due to +48.9% volume discrepancy.',
    tamperSealHash: 'f4e21a890123cb9837465012398475a890123475892301823904812039481234',
  },
  {
    id: 'AUD-2026-00939',
    timestamp: '2026-09-24 02:19:05 UTC',
    userId: 'sys-crypto-engine',
    userName: 'Cryptographic Engine',
    userRole: 'SYSTEM_ADMIN',
    action: 'EVIDENCE_SHA256_SEALED',
    targetEntity: 'EvidenceItem',
    targetId: 'EVD-2026-00412',
    ipAddress: '127.0.0.1 (Local Security Enclave)',
    details: 'Generated SHA-256 seal e3b0c442... for CCTV video capture from CAM-041.',
    tamperSealHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'AUD-2026-00938',
    timestamp: '2026-09-23 20:15:00 UTC',
    userId: 'usr-inv-44',
    userName: 'Inspector Marcus Reed',
    userRole: 'INVESTIGATOR',
    action: 'CASE_DOSSIER_OPENED',
    targetEntity: 'InvestigationCase',
    targetId: 'CASE-2026-0089',
    ipAddress: '10.14.88.19 (Station Workstation)',
    details: 'Opened formal case dossier CASE-2026-0089 for organized timber syndicate investigation in Northern Canopy.',
    tamperSealHash: '7281940a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e',
  },
];
